//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tien_EL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tien_EL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Tien_EL", typeof(Tien_EL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string barIn {
            get {
                return ResourceManager.GetString("barIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string barstDong {
            get {
                return ResourceManager.GetString("barstDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string barSTluu {
            get {
                return ResourceManager.GetString("barSTluu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Paid Money.
        /// </summary>
        internal static string barSuaTien {
            get {
                return ResourceManager.GetString("barSuaTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Money.
        /// </summary>
        internal static string barThuTien {
            get {
                return ResourceManager.GetString("barThuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay money.
        /// </summary>
        internal static string barTraTien {
            get {
                return ResourceManager.GetString("barTraTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain.
        /// </summary>
        internal static string colCònlại {
            get {
                return ResourceManager.GetString("colCònlại", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Bill.
        /// </summary>
        internal static string colMãhóađơnnhập {
            get {
                return ResourceManager.GetString("colMãhóađơnnhập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Bill.
        /// </summary>
        internal static string colMãhóađơnxuất {
            get {
                return ResourceManager.GetString("colMãhóađơnxuất", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Bill.
        /// </summary>
        internal static string colMãhóađơnxuất1 {
            get {
                return ResourceManager.GetString("colMãhóađơnxuất1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custommer Id.
        /// </summary>
        internal static string colMãkháchhàng {
            get {
                return ResourceManager.GetString("colMãkháchhàng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider ID.
        /// </summary>
        internal static string colMãnhàcungcấp {
            get {
                return ResourceManager.GetString("colMãnhàcungcấp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        internal static string colMãnhânviên {
            get {
                return ResourceManager.GetString("colMãnhânviên", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Note ID.
        /// </summary>
        internal static string colMãphiếuchi {
            get {
                return ResourceManager.GetString("colMãphiếuchi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Note Id.
        /// </summary>
        internal static string colMãphiếuthu {
            get {
                return ResourceManager.GetString("colMãphiếuthu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string colNgàychi {
            get {
                return ResourceManager.GetString("colNgàychi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string colNgàythu {
            get {
                return ResourceManager.GetString("colNgàythu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custommer Name.
        /// </summary>
        internal static string colTênkháchhàng {
            get {
                return ResourceManager.GetString("colTênkháchhàng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        internal static string colTênnhàcungcấp {
            get {
                return ResourceManager.GetString("colTênnhàcungcấp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Money .
        /// </summary>
        internal static string colTiềnđãtrả {
            get {
                return ResourceManager.GetString("colTiềnđãtrả", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Money.
        /// </summary>
        internal static string colTiềnđãtrả1 {
            get {
                return ResourceManager.GetString("colTiềnđãtrả1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total money.
        /// </summary>
        internal static string colTiềnphảitrả {
            get {
                return ResourceManager.GetString("colTiềnphảitrả", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custommer Detb.
        /// </summary>
        internal static string groupControl1 {
            get {
                return ResourceManager.GetString("groupControl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Money Custommer.
        /// </summary>
        internal static string groupControl2 {
            get {
                return ResourceManager.GetString("groupControl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string groupCtDetails {
            get {
                return ResourceManager.GetString("groupCtDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Money Infomation.
        /// </summary>
        internal static string groupCtInFo {
            get {
                return ResourceManager.GetString("groupCtInFo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lbDiachi {
            get {
                return ResourceManager.GetString("lbDiachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string lbDT {
            get {
                return ResourceManager.GetString("lbDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string lbFax {
            get {
                return ResourceManager.GetString("lbFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Bill.
        /// </summary>
        internal static string lbhdn {
            get {
                return ResourceManager.GetString("lbhdn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Bill.
        /// </summary>
        internal static string lbhdx {
            get {
                return ResourceManager.GetString("lbhdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custommer.
        /// </summary>
        internal static string lbKhachHang {
            get {
                return ResourceManager.GetString("lbKhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lbNgaylap {
            get {
                return ResourceManager.GetString("lbNgaylap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant.
        /// </summary>
        internal static string lbNgLap {
            get {
                return ResourceManager.GetString("lbNgLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date..../Month..../Year.....
        /// </summary>
        internal static string lbNTN {
            get {
                return ResourceManager.GetString("lbNTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        internal static string lbNV {
            get {
                return ResourceManager.GetString("lbNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check bill.
        /// </summary>
        internal static string lbPC {
            get {
                return ResourceManager.GetString("lbPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Note Id.
        /// </summary>
        internal static string lbPT {
            get {
                return ResourceManager.GetString("lbPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detb Money.
        /// </summary>
        internal static string lbTienno {
            get {
                return ResourceManager.GetString("lbTienno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Money.
        /// </summary>
        internal static string lbTratien {
            get {
                return ResourceManager.GetString("lbTratien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Provider.
        /// </summary>
        internal static string xrLbTieude {
            get {
                return ResourceManager.GetString("xrLbTieude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custommer&apos;s Debt.
        /// </summary>
        internal static string xrLbTieude1 {
            get {
                return ResourceManager.GetString("xrLbTieude1", resourceCulture);
            }
        }
    }
}
