//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlykho {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LamEL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LamEL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quanlykho.LamEL", typeof(LamEL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string CHECKTINHTRANG {
            get {
                return ResourceManager.GetString("CHECKTINHTRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string CHUCVU {
            get {
                return ResourceManager.GetString("CHUCVU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please Enter The Information Capture Force.
        /// </summary>
        internal static string CHUY {
            get {
                return ResourceManager.GetString("CHUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string DIACHI {
            get {
                return ResourceManager.GetString("DIACHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string DONG {
            get {
                return ResourceManager.GetString("DONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        internal static string DTDD {
            get {
                return ResourceManager.GetString("DTDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string DVT {
            get {
                return ResourceManager.GetString("DVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string GHICHU {
            get {
                return ResourceManager.GetString("GHICHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price.
        /// </summary>
        internal static string GIABAN {
            get {
                return ResourceManager.GetString("GIABAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying Price .
        /// </summary>
        internal static string GIAMUA {
            get {
                return ResourceManager.GetString("GIAMUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string HANSUDUNG {
            get {
                return ResourceManager.GetString("HANSUDUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string HINHANH {
            get {
                return ResourceManager.GetString("HINHANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILL&apos;S.
        /// </summary>
        internal static string HOADONXUAT {
            get {
                return ResourceManager.GetString("HOADONXUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string LUU {
            get {
                return ResourceManager.GetString("LUU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posibility ID .
        /// </summary>
        internal static string MABP {
            get {
                return ResourceManager.GetString("MABP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit ID.
        /// </summary>
        internal static string MADVT {
            get {
                return ResourceManager.GetString("MADVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custommer ID.
        /// </summary>
        internal static string MAKH {
            get {
                return ResourceManager.GetString("MAKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store ID.
        /// </summary>
        internal static string MAKHO {
            get {
                return ResourceManager.GetString("MAKHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area ID.
        /// </summary>
        internal static string MAKV {
            get {
                return ResourceManager.GetString("MAKV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string MAMH {
            get {
                return ResourceManager.GetString("MAMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider ID.
        /// </summary>
        internal static string MANCC {
            get {
                return ResourceManager.GetString("MANCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Products ID.
        /// </summary>
        internal static string MANH {
            get {
                return ResourceManager.GetString("MANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string MANV {
            get {
                return ResourceManager.GetString("MANV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager ID.
        /// </summary>
        internal static string MAQL {
            get {
                return ResourceManager.GetString("MAQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        internal static string MASOTHUE {
            get {
                return ResourceManager.GetString("MASOTHUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        internal static string MATH {
            get {
                return ResourceManager.GetString("MATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe.
        /// </summary>
        internal static string MOTA {
            get {
                return ResourceManager.GetString("MOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refesh.
        /// </summary>
        internal static string NAPLAI {
            get {
                return ResourceManager.GetString("NAPLAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string NGANHANG {
            get {
                return ResourceManager.GetString("NGANHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string NGAYSINH {
            get {
                return ResourceManager.GetString("NGAYSINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string NGUOILIENHE {
            get {
                return ResourceManager.GetString("NGUOILIENHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string NHAPDULIEU {
            get {
                return ResourceManager.GetString("NHAPDULIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Products.
        /// </summary>
        internal static string NHOMHANG {
            get {
                return ResourceManager.GetString("NHOMHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password Again.
        /// </summary>
        internal static string PASSWORD1 {
            get {
                return ResourceManager.GetString("PASSWORD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture .
        /// </summary>
        internal static string PICTURE {
            get {
                return ResourceManager.GetString("PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID People.
        /// </summary>
        internal static string SCMND {
            get {
                return ResourceManager.GetString("SCMND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        internal static string SDT {
            get {
                return ResourceManager.GetString("SDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dest Phone.
        /// </summary>
        internal static string SDTB {
            get {
                return ResourceManager.GetString("SDTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        internal static string SKYPE {
            get {
                return ResourceManager.GetString("SKYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string SOLUONG {
            get {
                return ResourceManager.GetString("SOLUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Product.
        /// </summary>
        internal static string SOLUONGMH {
            get {
                return ResourceManager.GetString("SOLUONGMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string SOTAIKHOAN {
            get {
                return ResourceManager.GetString("SOTAIKHOAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Tax.
        /// </summary>
        internal static string SOTHUE {
            get {
                return ResourceManager.GetString("SOTHUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string SUA {
            get {
                return ResourceManager.GetString("SUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posibility Name.
        /// </summary>
        internal static string TENBP {
            get {
                return ResourceManager.GetString("TENBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custommer Name.
        /// </summary>
        internal static string TENKH {
            get {
                return ResourceManager.GetString("TENKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        internal static string TENKHO {
            get {
                return ResourceManager.GetString("TENKHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name.
        /// </summary>
        internal static string TENKV {
            get {
                return ResourceManager.GetString("TENKV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string TENMH {
            get {
                return ResourceManager.GetString("TENMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        internal static string TENNCC {
            get {
                return ResourceManager.GetString("TENNCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Products Name.
        /// </summary>
        internal static string TENNHOMHANG {
            get {
                return ResourceManager.GetString("TENNHOMHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string TENNV {
            get {
                return ResourceManager.GetString("TENNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Name.
        /// </summary>
        internal static string TENQL {
            get {
                return ResourceManager.GetString("TENQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string THEM {
            get {
                return ResourceManager.GetString("THEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string THOAT {
            get {
                return ResourceManager.GetString("THOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to summary.
        /// </summary>
        internal static string THONGKETONGHOP {
            get {
                return ResourceManager.GetString("THONGKETONGHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TINHTRANG {
            get {
                return ResourceManager.GetString("TINHTRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string WEBSITE {
            get {
                return ResourceManager.GetString("WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string XOA {
            get {
                return ResourceManager.GetString("XOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Data.
        /// </summary>
        internal static string XUATDULIEU {
            get {
                return ResourceManager.GetString("XUATDULIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo.
        /// </summary>
        internal static string YAHOO {
            get {
                return ResourceManager.GetString("YAHOO", resourceCulture);
            }
        }
    }
}
