//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resVietNam {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resVietNam() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.resVietNam", typeof(resVietNam).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương Trình Quản Lý Xuất - Nhập - Tồn.
        /// </summary>
        internal static string barChuongTrinh {
            get {
                return ResourceManager.GetString("barChuongTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương Trình Quản Lý Xuất - Nhập - Tồn.
        /// </summary>
        internal static string barChuongTrinh1 {
            get {
                return ResourceManager.GetString("barChuongTrinh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương Trình Quản Lý Xuất - Nhập - Tồn.
        /// </summary>
        internal static string barChuongTrinh11 {
            get {
                return ResourceManager.GetString("barChuongTrinh11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        internal static string btBoPhan {
            get {
                return ResourceManager.GetString("btBoPhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        internal static string btBoPhan1 {
            get {
                return ResourceManager.GetString("btBoPhan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        internal static string btBoPhan11 {
            get {
                return ResourceManager.GetString("btBoPhan11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu Tiền.
        /// </summary>
        internal static string btCongNoKH {
            get {
                return ResourceManager.GetString("btCongNoKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string btCongNoKH1 {
            get {
                return ResourceManager.GetString("btCongNoKH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string btCongNoKH11 {
            get {
                return ResourceManager.GetString("btCongNoKH11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả Tiền.
        /// </summary>
        internal static string btCongNoNCC {
            get {
                return ResourceManager.GetString("btCongNoNCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string btCongNoNCC1 {
            get {
                return ResourceManager.GetString("btCongNoNCC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string btCongNoNCC11 {
            get {
                return ResourceManager.GetString("btCongNoNCC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string btDangXuat {
            get {
                return ResourceManager.GetString("btDangXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string btDangXuat1 {
            get {
                return ResourceManager.GetString("btDangXuat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string btDangXuat11 {
            get {
                return ResourceManager.GetString("btDangXuat11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        internal static string btDanhSachNV {
            get {
                return ResourceManager.GetString("btDanhSachNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        internal static string btDanhSachNV1 {
            get {
                return ResourceManager.GetString("btDanhSachNV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        internal static string btDanhSachNV11 {
            get {
                return ResourceManager.GetString("btDanhSachNV11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh thu.
        /// </summary>
        internal static string btDoanhThu {
            get {
                return ResourceManager.GetString("btDoanhThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh thu.
        /// </summary>
        internal static string btDoanhThu1 {
            get {
                return ResourceManager.GetString("btDoanhThu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh thu.
        /// </summary>
        internal static string btDoanhThu11 {
            get {
                return ResourceManager.GetString("btDoanhThu11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string btDoiMatKhau {
            get {
                return ResourceManager.GetString("btDoiMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string btDoiMatKhau1 {
            get {
                return ResourceManager.GetString("btDoiMatKhau1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string btDoiMatKhau11 {
            get {
                return ResourceManager.GetString("btDoiMatKhau11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string btDong {
            get {
                return ResourceManager.GetString("btDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string btDong1 {
            get {
                return ResourceManager.GetString("btDong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string btDong11 {
            get {
                return ResourceManager.GetString("btDong11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        internal static string btDonViTinh {
            get {
                return ResourceManager.GetString("btDonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        internal static string btDonViTinh1 {
            get {
                return ResourceManager.GetString("btDonViTinh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Vị Tính.
        /// </summary>
        internal static string btDonViTinh11 {
            get {
                return ResourceManager.GetString("btDonViTinh11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoá đơn nhập.
        /// </summary>
        internal static string btHoaDonNhap {
            get {
                return ResourceManager.GetString("btHoaDonNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoá đơn nhập.
        /// </summary>
        internal static string btHoaDonNhap1 {
            get {
                return ResourceManager.GetString("btHoaDonNhap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoá đơn nhập.
        /// </summary>
        internal static string btHoaDonNhap11 {
            get {
                return ResourceManager.GetString("btHoaDonNhap11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoá đơn xuất.
        /// </summary>
        internal static string btHoaDonXuat {
            get {
                return ResourceManager.GetString("btHoaDonXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoá đơn xuất.
        /// </summary>
        internal static string btHoaDonXuat1 {
            get {
                return ResourceManager.GetString("btHoaDonXuat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoá đơn xuất.
        /// </summary>
        internal static string btHoaDonXuat11 {
            get {
                return ResourceManager.GetString("btHoaDonXuat11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        internal static string btHuongDan {
            get {
                return ResourceManager.GetString("btHuongDan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        internal static string btHuongDan1 {
            get {
                return ResourceManager.GetString("btHuongDan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        internal static string btHuongDan11 {
            get {
                return ResourceManager.GetString("btHuongDan11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string btIn {
            get {
                return ResourceManager.GetString("btIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string btIn1 {
            get {
                return ResourceManager.GetString("btIn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string btIn11 {
            get {
                return ResourceManager.GetString("btIn11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        internal static string btKetThuc {
            get {
                return ResourceManager.GetString("btKetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        internal static string btKetThuc1 {
            get {
                return ResourceManager.GetString("btKetThuc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        internal static string btKetThuc11 {
            get {
                return ResourceManager.GetString("btKetThuc11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string btKhachHang {
            get {
                return ResourceManager.GetString("btKhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string btKhachHang1 {
            get {
                return ResourceManager.GetString("btKhachHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách Hàng.
        /// </summary>
        internal static string btKhachHang11 {
            get {
                return ResourceManager.GetString("btKhachHang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string btKho {
            get {
                return ResourceManager.GetString("btKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string btKho1 {
            get {
                return ResourceManager.GetString("btKho1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string btKho11 {
            get {
                return ResourceManager.GetString("btKho11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        internal static string btKhuVuc {
            get {
                return ResourceManager.GetString("btKhuVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        internal static string btKhuVuc1 {
            get {
                return ResourceManager.GetString("btKhuVuc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        internal static string btKhuVuc11 {
            get {
                return ResourceManager.GetString("btKhuVuc11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string btLienHe {
            get {
                return ResourceManager.GetString("btLienHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string btLienHe1 {
            get {
                return ResourceManager.GetString("btLienHe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string btLienHe11 {
            get {
                return ResourceManager.GetString("btLienHe11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string btLuu {
            get {
                return ResourceManager.GetString("btLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string btLuu1 {
            get {
                return ResourceManager.GetString("btLuu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn Kho.
        /// </summary>
        internal static string btMatHang {
            get {
                return ResourceManager.GetString("btMatHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hoá.
        /// </summary>
        internal static string btMatHang1 {
            get {
                return ResourceManager.GetString("btMatHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hoá.
        /// </summary>
        internal static string btMatHang11 {
            get {
                return ResourceManager.GetString("btMatHang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string btNhaCungCap {
            get {
                return ResourceManager.GetString("btNhaCungCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string btNhaCungCap1 {
            get {
                return ResourceManager.GetString("btNhaCungCap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string btNhaCungCap11 {
            get {
                return ResourceManager.GetString("btNhaCungCap11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string btNhanVien {
            get {
                return ResourceManager.GetString("btNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string btNhanVien1 {
            get {
                return ResourceManager.GetString("btNhanVien1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string btNhanVien11 {
            get {
                return ResourceManager.GetString("btNhanVien11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập hàng.
        /// </summary>
        internal static string btNhapHang {
            get {
                return ResourceManager.GetString("btNhapHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập hàng.
        /// </summary>
        internal static string btNhapHang1 {
            get {
                return ResourceManager.GetString("btNhapHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập hàng.
        /// </summary>
        internal static string btNhapHang11 {
            get {
                return ResourceManager.GetString("btNhapHang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng.
        /// </summary>
        internal static string btNhomHang {
            get {
                return ResourceManager.GetString("btNhomHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng.
        /// </summary>
        internal static string btNhomHang1 {
            get {
                return ResourceManager.GetString("btNhomHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng.
        /// </summary>
        internal static string btNhomHang11 {
            get {
                return ResourceManager.GetString("btNhomHang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        internal static string btPhanQuyen {
            get {
                return ResourceManager.GetString("btPhanQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        internal static string btPhanQuyen1 {
            get {
                return ResourceManager.GetString("btPhanQuyen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        internal static string btPhanQuyen11 {
            get {
                return ResourceManager.GetString("btPhanQuyen11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phục hồi.
        /// </summary>
        internal static string btPhucHoi {
            get {
                return ResourceManager.GetString("btPhucHoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phục hồi.
        /// </summary>
        internal static string btPhucHoi1 {
            get {
                return ResourceManager.GetString("btPhucHoi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phục hồi.
        /// </summary>
        internal static string btPhucHoi11 {
            get {
                return ResourceManager.GetString("btPhucHoi11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu.
        /// </summary>
        internal static string btSaoLuu {
            get {
                return ResourceManager.GetString("btSaoLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu.
        /// </summary>
        internal static string btSaoLuu1 {
            get {
                return ResourceManager.GetString("btSaoLuu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu.
        /// </summary>
        internal static string btSaoLuu11 {
            get {
                return ResourceManager.GetString("btSaoLuu11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        internal static string btTacGia {
            get {
                return ResourceManager.GetString("btTacGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        internal static string btTacGia1 {
            get {
                return ResourceManager.GetString("btTacGia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        internal static string btTacGia11 {
            get {
                return ResourceManager.GetString("btTacGia11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string btThongTin {
            get {
                return ResourceManager.GetString("btThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string btThongTin1 {
            get {
                return ResourceManager.GetString("btThongTin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string btThongTin11 {
            get {
                return ResourceManager.GetString("btThongTin11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp.
        /// </summary>
        internal static string btTongHop {
            get {
                return ResourceManager.GetString("btTongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp.
        /// </summary>
        internal static string btTongHop1 {
            get {
                return ResourceManager.GetString("btTongHop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp.
        /// </summary>
        internal static string btTongHop11 {
            get {
                return ResourceManager.GetString("btTongHop11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho.
        /// </summary>
        internal static string btTonKho {
            get {
                return ResourceManager.GetString("btTonKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho.
        /// </summary>
        internal static string btTonKho1 {
            get {
                return ResourceManager.GetString("btTonKho1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho.
        /// </summary>
        internal static string btTonKho11 {
            get {
                return ResourceManager.GetString("btTonKho11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        internal static string btXem {
            get {
                return ResourceManager.GetString("btXem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        internal static string btXem1 {
            get {
                return ResourceManager.GetString("btXem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        internal static string btXem11 {
            get {
                return ResourceManager.GetString("btXem11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất excel.
        /// </summary>
        internal static string btXuat {
            get {
                return ResourceManager.GetString("btXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất excel.
        /// </summary>
        internal static string btXuat1 {
            get {
                return ResourceManager.GetString("btXuat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất excel.
        /// </summary>
        internal static string btXuat11 {
            get {
                return ResourceManager.GetString("btXuat11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất hàng.
        /// </summary>
        internal static string btXuatHang {
            get {
                return ResourceManager.GetString("btXuatHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất hàng.
        /// </summary>
        internal static string btXuatHang1 {
            get {
                return ResourceManager.GetString("btXuatHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất hàng.
        /// </summary>
        internal static string btXuatHang11 {
            get {
                return ResourceManager.GetString("btXuatHang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhẩu tài khoản và mật khẩu.
        /// </summary>
        internal static string checkNho {
            get {
                return ResourceManager.GetString("checkNho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        internal static string coldongia {
            get {
                return ResourceManager.GetString("coldongia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        internal static string colDonViTInh {
            get {
                return ResourceManager.GetString("colDonViTInh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        internal static string colDonViTInh1 {
            get {
                return ResourceManager.GetString("colDonViTInh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        internal static string colDonViTInh11 {
            get {
                return ResourceManager.GetString("colDonViTInh11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        internal static string colDonViTInh111 {
            get {
                return ResourceManager.GetString("colDonViTInh111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán.
        /// </summary>
        internal static string colgiaban {
            get {
                return ResourceManager.GetString("colgiaban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giá mua.
        /// </summary>
        internal static string colgiamua {
            get {
                return ResourceManager.GetString("colgiamua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền Nhập.
        /// </summary>
        internal static string COLGIAVON {
            get {
                return ResourceManager.GetString("COLGIAVON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hoá.
        /// </summary>
        internal static string colHangHoa {
            get {
                return ResourceManager.GetString("colHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hoá.
        /// </summary>
        internal static string colHangHoa1 {
            get {
                return ResourceManager.GetString("colHangHoa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hoá.
        /// </summary>
        internal static string colHangHoa11 {
            get {
                return ResourceManager.GetString("colHangHoa11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string colHangHoa111 {
            get {
                return ResourceManager.GetString("colHangHoa111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn sử dụng.
        /// </summary>
        internal static string colhansudung {
            get {
                return ResourceManager.GetString("colhansudung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string colhinhanh {
            get {
                return ResourceManager.GetString("colhinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        internal static string colKhachHang {
            get {
                return ResourceManager.GetString("colKhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        internal static string colKhachHang1 {
            get {
                return ResourceManager.GetString("colKhachHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string colkhachhang11 {
            get {
                return ResourceManager.GetString("colkhachhang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string colkho {
            get {
                return ResourceManager.GetString("colkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lợi Nhuận.
        /// </summary>
        internal static string colloinhuan {
            get {
                return ResourceManager.GetString("colloinhuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng.
        /// </summary>
        internal static string colMa {
            get {
                return ResourceManager.GetString("colMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng.
        /// </summary>
        internal static string colMa1 {
            get {
                return ResourceManager.GetString("colMa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng.
        /// </summary>
        internal static string colMa11 {
            get {
                return ResourceManager.GetString("colMa11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string colMa111 {
            get {
                return ResourceManager.GetString("colMa111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng.
        /// </summary>
        internal static string colmahang {
            get {
                return ResourceManager.GetString("colmahang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hóa đơn.
        /// </summary>
        internal static string COLMAHDX {
            get {
                return ResourceManager.GetString("COLMAHDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm hàng.
        /// </summary>
        internal static string colmamhathangg1 {
            get {
                return ResourceManager.GetString("colmamhathangg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Mặt Hàng.
        /// </summary>
        internal static string colmathang {
            get {
                return ResourceManager.GetString("colmathang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô Tả.
        /// </summary>
        internal static string colmota {
            get {
                return ResourceManager.GetString("colmota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string colNgay {
            get {
                return ResourceManager.GetString("colNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string colNgay1 {
            get {
                return ResourceManager.GetString("colNgay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string colngay11 {
            get {
                return ResourceManager.GetString("colngay11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string colNgay111 {
            get {
                return ResourceManager.GetString("colNgay111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string colngayxuat {
            get {
                return ResourceManager.GetString("colngayxuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng.
        /// </summary>
        internal static string colNhomHang {
            get {
                return ResourceManager.GetString("colNhomHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng.
        /// </summary>
        internal static string colNhomHang1 {
            get {
                return ResourceManager.GetString("colNhomHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng.
        /// </summary>
        internal static string colNhomHang11 {
            get {
                return ResourceManager.GetString("colNhomHang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group product.
        /// </summary>
        internal static string colNhomHang111 {
            get {
                return ResourceManager.GetString("colNhomHang111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng đầu.
        /// </summary>
        internal static string colSLDau1 {
            get {
                return ResourceManager.GetString("colSLDau1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhập.
        /// </summary>
        internal static string colSLNhap1 {
            get {
                return ResourceManager.GetString("colSLNhap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng tồn.
        /// </summary>
        internal static string colSLTOn1 {
            get {
                return ResourceManager.GetString("colSLTOn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng xuất.
        /// </summary>
        internal static string colSLXuat1 {
            get {
                return ResourceManager.GetString("colSLXuat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Lượng.
        /// </summary>
        internal static string colsoluong {
            get {
                return ResourceManager.GetString("colsoluong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Lượng.
        /// </summary>
        internal static string colsoluongmh {
            get {
                return ResourceManager.GetString("colsoluongmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Ngày Còn Hạn.
        /// </summary>
        internal static string colsongayconhan {
            get {
                return ResourceManager.GetString("colsongayconhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Vị Tính.
        /// </summary>
        internal static string coltendonvi {
            get {
                return ResourceManager.GetString("coltendonvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khu vực.
        /// </summary>
        internal static string colTenKhuVuc {
            get {
                return ResourceManager.GetString("colTenKhuVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khu vực.
        /// </summary>
        internal static string colTenKhuVuc1 {
            get {
                return ResourceManager.GetString("colTenKhuVuc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Mặt Hàng.
        /// </summary>
        internal static string coltenmathang {
            get {
                return ResourceManager.GetString("coltenmathang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Nhóm.
        /// </summary>
        internal static string coltennhomhang {
            get {
                return ResourceManager.GetString("coltennhomhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string colthanhtien {
            get {
                return ResourceManager.GetString("colthanhtien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng Tiền Nhập.
        /// </summary>
        internal static string colthanhtiennhap {
            get {
                return ResourceManager.GetString("colthanhtiennhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tông Tiền Bán.
        /// </summary>
        internal static string colthanhtienxuat {
            get {
                return ResourceManager.GetString("colthanhtienxuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế.
        /// </summary>
        internal static string colthue {
            get {
                return ResourceManager.GetString("colthue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Thuế GTGT.
        /// </summary>
        internal static string colthueGTGT {
            get {
                return ResourceManager.GetString("colthueGTGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền Bán.
        /// </summary>
        internal static string coltienban {
            get {
                return ResourceManager.GetString("coltienban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình Trạng.
        /// </summary>
        internal static string coltinhtrang {
            get {
                return ResourceManager.GetString("coltinhtrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng doanh thu.
        /// </summary>
        internal static string colTongDanhThu {
            get {
                return ResourceManager.GetString("colTongDanhThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng doanh thu.
        /// </summary>
        internal static string colTongDanhThu1 {
            get {
                return ResourceManager.GetString("colTongDanhThu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng doanh thu.
        /// </summary>
        internal static string colTongDanhThu11 {
            get {
                return ResourceManager.GetString("colTongDanhThu11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string DangNhap {
            get {
                return ResourceManager.GetString("DangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Kho.
        /// </summary>
        internal static string frmMain {
            get {
                return ResourceManager.GetString("frmMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Kho.
        /// </summary>
        internal static string frmMain1 {
            get {
                return ResourceManager.GetString("frmMain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Kho.
        /// </summary>
        internal static string frmMain11 {
            get {
                return ResourceManager.GetString("frmMain11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuối kì.
        /// </summary>
        internal static string gridCuoiKi {
            get {
                return ResourceManager.GetString("gridCuoiKi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuối kì.
        /// </summary>
        internal static string gridCuoiKi1 {
            get {
                return ResourceManager.GetString("gridCuoiKi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuối kì.
        /// </summary>
        internal static string gridCuoiKi11 {
            get {
                return ResourceManager.GetString("gridCuoiKi11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu kì.
        /// </summary>
        internal static string gridDauKi {
            get {
                return ResourceManager.GetString("gridDauKi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu kì.
        /// </summary>
        internal static string gridDauKi1 {
            get {
                return ResourceManager.GetString("gridDauKi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu kì.
        /// </summary>
        internal static string gridDauKi11 {
            get {
                return ResourceManager.GetString("gridDauKi11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kho.
        /// </summary>
        internal static string gridNhapKho {
            get {
                return ResourceManager.GetString("gridNhapKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kho.
        /// </summary>
        internal static string gridNhapKho1 {
            get {
                return ResourceManager.GetString("gridNhapKho1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kho.
        /// </summary>
        internal static string gridNhapKho11 {
            get {
                return ResourceManager.GetString("gridNhapKho11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin mặt hàng.
        /// </summary>
        internal static string gridThongTin {
            get {
                return ResourceManager.GetString("gridThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin mặt hàng.
        /// </summary>
        internal static string gridThongTin1 {
            get {
                return ResourceManager.GetString("gridThongTin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin mặt hàng.
        /// </summary>
        internal static string gridThongTin11 {
            get {
                return ResourceManager.GetString("gridThongTin11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất kho.
        /// </summary>
        internal static string gridXuatKho {
            get {
                return ResourceManager.GetString("gridXuatKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất kho.
        /// </summary>
        internal static string gridXuatKho1 {
            get {
                return ResourceManager.GetString("gridXuatKho1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất kho.
        /// </summary>
        internal static string gridXuatKho11 {
            get {
                return ResourceManager.GetString("gridXuatKho11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo doanh thu.
        /// </summary>
        internal static string lbBaoCaoDoanhThu {
            get {
                return ResourceManager.GetString("lbBaoCaoDoanhThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo doanh thu.
        /// </summary>
        internal static string lbBaoCaoDoanhThu1 {
            get {
                return ResourceManager.GetString("lbBaoCaoDoanhThu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỐNG KÊ LỢI NHUẬN.
        /// </summary>
        internal static string lbBaoCaoLOINHUAN {
            get {
                return ResourceManager.GetString("lbBaoCaoLOINHUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỐNG KÊ MẶT HÀNG.
        /// </summary>
        internal static string lbBaoCaoMATHANG {
            get {
                return ResourceManager.GetString("lbBaoCaoMATHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỐNG KÊ THEO KHO.
        /// </summary>
        internal static string lbBaoCaotheokho {
            get {
                return ResourceManager.GetString("lbBaoCaotheokho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhóm.
        /// </summary>
        internal static string lbchonnhom {
            get {
                return ResourceManager.GetString("lbchonnhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến.
        /// </summary>
        internal static string lbden {
            get {
                return ResourceManager.GetString("lbden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ :.
        /// </summary>
        internal static string lbDiaChi {
            get {
                return ResourceManager.GetString("lbDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ :.
        /// </summary>
        internal static string lbDiaChi1 {
            get {
                return ResourceManager.GetString("lbDiaChi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên file.
        /// </summary>
        internal static string lbDienTen {
            get {
                return ResourceManager.GetString("lbDienTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên file.
        /// </summary>
        internal static string lbDienTen1 {
            get {
                return ResourceManager.GetString("lbDienTen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại :.
        /// </summary>
        internal static string lbDienThoai {
            get {
                return ResourceManager.GetString("lbDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại :.
        /// </summary>
        internal static string lbDienThoai1 {
            get {
                return ResourceManager.GetString("lbDienThoai1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        internal static string lbDuongDan {
            get {
                return ResourceManager.GetString("lbDuongDan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        internal static string lbDuongDan1 {
            get {
                return ResourceManager.GetString("lbDuongDan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax :.
        /// </summary>
        internal static string lbFax {
            get {
                return ResourceManager.GetString("lbFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax :.
        /// </summary>
        internal static string lbFax1 {
            get {
                return ResourceManager.GetString("lbFax1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giám đốc.
        /// </summary>
        internal static string lbGiamDoc {
            get {
                return ResourceManager.GetString("lbGiamDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giám đốc.
        /// </summary>
        internal static string lbGiamDoc1 {
            get {
                return ResourceManager.GetString("lbGiamDoc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế toán.
        /// </summary>
        internal static string lbKeToan {
            get {
                return ResourceManager.GetString("lbKeToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế toán.
        /// </summary>
        internal static string lbKeToan1 {
            get {
                return ResourceManager.GetString("lbKeToan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho hàng :.
        /// </summary>
        internal static string lbKhoHang {
            get {
                return ResourceManager.GetString("lbKhoHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho hàng :.
        /// </summary>
        internal static string lbKhoHang1 {
            get {
                return ResourceManager.GetString("lbKhoHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Kí ghi rõ họ tên).
        /// </summary>
        internal static string lbKiTen {
            get {
                return ResourceManager.GetString("lbKiTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Kí ghi rõ họ tên).
        /// </summary>
        internal static string lbKiTen1 {
            get {
                return ResourceManager.GetString("lbKiTen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại Hiển Thị.
        /// </summary>
        internal static string lbloai {
            get {
                return ResourceManager.GetString("lbloai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        internal static string lbNam {
            get {
                return ResourceManager.GetString("lbNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        internal static string lbNam1 {
            get {
                return ResourceManager.GetString("lbNam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày...tháng...Năm....
        /// </summary>
        internal static string lbNgayThang {
            get {
                return ResourceManager.GetString("lbNgayThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày...tháng...Năm....
        /// </summary>
        internal static string lbNgayThang1 {
            get {
                return ResourceManager.GetString("lbNgayThang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người lập.
        /// </summary>
        internal static string lbNguoiLap {
            get {
                return ResourceManager.GetString("lbNguoiLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người lập.
        /// </summary>
        internal static string lbNguoiLap1 {
            get {
                return ResourceManager.GetString("lbNguoiLap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file.
        /// </summary>
        internal static string lbTenFile {
            get {
                return ResourceManager.GetString("lbTenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file.
        /// </summary>
        internal static string lbTenFile1 {
            get {
                return ResourceManager.GetString("lbTenFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỐNG KÊ NHÓM HÀNG.
        /// </summary>
        internal static string lbThongkenhmhang {
            get {
                return ResourceManager.GetString("lbThongkenhmhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp xuất nhập tồn.
        /// </summary>
        internal static string lbTieuDeTongHop {
            get {
                return ResourceManager.GetString("lbTieuDeTongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp xuất nhập tồn.
        /// </summary>
        internal static string lbTieuDeTongHop1 {
            get {
                return ResourceManager.GetString("lbTieuDeTongHop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ.
        /// </summary>
        internal static string lbtu {
            get {
                return ResourceManager.GetString("lbtu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Kho.
        /// </summary>
        internal static string linhtheokho {
            get {
                return ResourceManager.GetString("linhtheokho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Khách Hàng.
        /// </summary>
        internal static string linktheokhachhang {
            get {
                return ResourceManager.GetString("linktheokhachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Lợi Nhuận.
        /// </summary>
        internal static string linktheoloinhuan {
            get {
                return ResourceManager.GetString("linktheoloinhuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Mặt Hàng.
        /// </summary>
        internal static string linktheomathang {
            get {
                return ResourceManager.GetString("linktheomathang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo năm.
        /// </summary>
        internal static string linkTheoNam {
            get {
                return ResourceManager.GetString("linkTheoNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo năm.
        /// </summary>
        internal static string linkTheoNam1 {
            get {
                return ResourceManager.GetString("linkTheoNam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo ngày.
        /// </summary>
        internal static string linkTheoNgay {
            get {
                return ResourceManager.GetString("linkTheoNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo ngày.
        /// </summary>
        internal static string linkTheoNgay1 {
            get {
                return ResourceManager.GetString("linkTheoNgay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Nhóm Hàng.
        /// </summary>
        internal static string linktheonhomhang {
            get {
                return ResourceManager.GetString("linktheonhomhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo quí.
        /// </summary>
        internal static string linkTheoQui {
            get {
                return ResourceManager.GetString("linkTheoQui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo quí.
        /// </summary>
        internal static string linkTheoQui1 {
            get {
                return ResourceManager.GetString("linkTheoQui1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo tháng.
        /// </summary>
        internal static string linkTheoThang {
            get {
                return ResourceManager.GetString("linkTheoThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo tháng.
        /// </summary>
        internal static string linkTheoThang1 {
            get {
                return ResourceManager.GetString("linkTheoThang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kho.
        /// </summary>
        internal static string MaKho {
            get {
                return ResourceManager.GetString("MaKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kho.
        /// </summary>
        internal static string MaKho1 {
            get {
                return ResourceManager.GetString("MaKho1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực khách hàng.
        /// </summary>
        internal static string navBarKhachHang {
            get {
                return ResourceManager.GetString("navBarKhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực khách hàng.
        /// </summary>
        internal static string navBarKhachHang1 {
            get {
                return ResourceManager.GetString("navBarKhachHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống Kê.
        /// </summary>
        internal static string navthongke {
            get {
                return ResourceManager.GetString("navthongke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ :.
        /// </summary>
        internal static string NgayBD {
            get {
                return ResourceManager.GetString("NgayBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ :.
        /// </summary>
        internal static string NgayBD1 {
            get {
                return ResourceManager.GetString("NgayBD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến :.
        /// </summary>
        internal static string NgayKT {
            get {
                return ResourceManager.GetString("NgayKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến :.
        /// </summary>
        internal static string NgayKT1 {
            get {
                return ResourceManager.GetString("NgayKT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứ năng.
        /// </summary>
        internal static string nvaChucNang {
            get {
                return ResourceManager.GetString("nvaChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứ năng.
        /// </summary>
        internal static string nvaChucNang1 {
            get {
                return ResourceManager.GetString("nvaChucNang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo mật.
        /// </summary>
        internal static string ribBaoMat {
            get {
                return ResourceManager.GetString("ribBaoMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo mật.
        /// </summary>
        internal static string ribBaoMat1 {
            get {
                return ResourceManager.GetString("ribBaoMat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo mật.
        /// </summary>
        internal static string ribBaoMat11 {
            get {
                return ResourceManager.GetString("ribBaoMat11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        internal static string ribChucNang {
            get {
                return ResourceManager.GetString("ribChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        internal static string ribChucNang1 {
            get {
                return ResourceManager.GetString("ribChucNang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        internal static string ribChucNang11 {
            get {
                return ResourceManager.GetString("ribChucNang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string ribDanhMuc {
            get {
                return ResourceManager.GetString("ribDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string ribDanhMuc1 {
            get {
                return ResourceManager.GetString("ribDanhMuc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string ribDanhMuc11 {
            get {
                return ResourceManager.GetString("ribDanhMuc11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác.
        /// </summary>
        internal static string ribDoiTac {
            get {
                return ResourceManager.GetString("ribDoiTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác.
        /// </summary>
        internal static string ribDoiTac1 {
            get {
                return ResourceManager.GetString("ribDoiTac1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác.
        /// </summary>
        internal static string ribDoiTac11 {
            get {
                return ResourceManager.GetString("ribDoiTac11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu.
        /// </summary>
        internal static string ribDuLieu {
            get {
                return ResourceManager.GetString("ribDuLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu.
        /// </summary>
        internal static string ribDuLieu1 {
            get {
                return ResourceManager.GetString("ribDuLieu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu.
        /// </summary>
        internal static string ribDuLieu11 {
            get {
                return ResourceManager.GetString("ribDuLieu11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        internal static string ribHeThong {
            get {
                return ResourceManager.GetString("ribHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        internal static string ribHeThong1 {
            get {
                return ResourceManager.GetString("ribHeThong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        internal static string ribHeThong11 {
            get {
                return ResourceManager.GetString("ribHeThong11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        internal static string ribHeThongBar {
            get {
                return ResourceManager.GetString("ribHeThongBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        internal static string ribHeThongBar1 {
            get {
                return ResourceManager.GetString("ribHeThongBar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        internal static string ribHeThongBar11 {
            get {
                return ResourceManager.GetString("ribHeThongBar11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoá đơn.
        /// </summary>
        internal static string ribHoaDon {
            get {
                return ResourceManager.GetString("ribHoaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoá đơn.
        /// </summary>
        internal static string ribHoaDon1 {
            get {
                return ResourceManager.GetString("ribHoaDon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoá đơn.
        /// </summary>
        internal static string ribHoaDon11 {
            get {
                return ResourceManager.GetString("ribHoaDon11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho hàng.
        /// </summary>
        internal static string ribKhoHang {
            get {
                return ResourceManager.GetString("ribKhoHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho hàng.
        /// </summary>
        internal static string ribKhoHang1 {
            get {
                return ResourceManager.GetString("ribKhoHang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho hàng.
        /// </summary>
        internal static string ribKhoHang11 {
            get {
                return ResourceManager.GetString("ribKhoHang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string ribNhanVien {
            get {
                return ResourceManager.GetString("ribNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string ribNhanVien1 {
            get {
                return ResourceManager.GetString("ribNhanVien1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string ribNhanVien11 {
            get {
                return ResourceManager.GetString("ribNhanVien11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý công nợ.
        /// </summary>
        internal static string ribQLCongNo {
            get {
                return ResourceManager.GetString("ribQLCongNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý công nợ.
        /// </summary>
        internal static string ribQLCongNo1 {
            get {
                return ResourceManager.GetString("ribQLCongNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý công nợ.
        /// </summary>
        internal static string ribQLCongNo11 {
            get {
                return ResourceManager.GetString("ribQLCongNo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng Hoá.
        /// </summary>
        internal static string ribQLHangHoa {
            get {
                return ResourceManager.GetString("ribQLHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng Hoá.
        /// </summary>
        internal static string ribQLHangHoa1 {
            get {
                return ResourceManager.GetString("ribQLHangHoa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng Hoá.
        /// </summary>
        internal static string ribQLHangHoa11 {
            get {
                return ResourceManager.GetString("ribQLHangHoa11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        internal static string ribThongke {
            get {
                return ResourceManager.GetString("ribThongke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        internal static string ribThongke1 {
            get {
                return ResourceManager.GetString("ribThongke1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        internal static string ribThongke11 {
            get {
                return ResourceManager.GetString("ribThongke11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        internal static string ribTroGiup {
            get {
                return ResourceManager.GetString("ribTroGiup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        internal static string ribTroGiup1 {
            get {
                return ResourceManager.GetString("ribTroGiup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        internal static string ribTroGiup11 {
            get {
                return ResourceManager.GetString("ribTroGiup11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        internal static string ribTroGiupBar {
            get {
                return ResourceManager.GetString("ribTroGiupBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        internal static string ribTroGiupBar1 {
            get {
                return ResourceManager.GetString("ribTroGiupBar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        internal static string ribTroGiupBar11 {
            get {
                return ResourceManager.GetString("ribTroGiupBar11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string SoLuong {
            get {
                return ResourceManager.GetString("SoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string SoLuong1 {
            get {
                return ResourceManager.GetString("SoLuong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string SoLuong11 {
            get {
                return ResourceManager.GetString("SoLuong11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kho.
        /// </summary>
        internal static string TenKho {
            get {
                return ResourceManager.GetString("TenKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kho.
        /// </summary>
        internal static string TenKho1 {
            get {
                return ResourceManager.GetString("TenKho1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string Thoat {
            get {
                return ResourceManager.GetString("Thoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string TongCong {
            get {
                return ResourceManager.GetString("TongCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string TongCong1 {
            get {
                return ResourceManager.GetString("TongCong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string TongCong11 {
            get {
                return ResourceManager.GetString("TongCong11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuỳ chọn.
        /// </summary>
        internal static string TuyChon {
            get {
                return ResourceManager.GetString("TuyChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
    }
}
