USE KHO_VINAVETCO

DELETE MAHDARRAY WHERE MAHD IN(SELECT MAHDN FROM HOADONNHAP,MAHDARRAY WHERE MAHDARRAY.MAHD=HOADONNHAP.MAHDN)
GO
SELECT CASE WHEN (SELECT MAHD FROM MAHDARRAY WHERE TYPE='MAHDN' AND IDUSER='NV00001')  IS NULL THEN 'MAHDN' + convert(VARCHAR,(SELECT MAX(convert(int,SUBSTRING(MAHDN,6,len(MAHDN)-5))) FROM HOADONNHAP)+1) ELSE (SELECT MAHD FROM MAHDARRAY) END 