using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
//using MySql.Data.MySqlClient;
using System.Configuration;

namespace WindowsFormsApplication1
{

    class clDao:Provider
    {
  
        public DataTable kiemtra_user(clDTO dto)
        {
            String SQL = "select * from NHANVIEN where USERNAMES='"+dto.TENDANGNHAP+"'";
            return getdata(SQL);
        }

        public void addMatHang(clDTO dto)
        {
            String SQL = "insert into MATHANG(MAMH,MATH,MANH,MAKHO,TENMH,MADVT,SOLUONGMH,HANSUDUNG,GIAMUA,GIABAN, MOTA,TINHTRANG)"
            +" values( '"+dto.MAMH +"','"+ dto.MATH+"','"+dto.MANH+"','"+dto.MAKHO+"','"+dto.TENMH+"','"+dto.MADVT+"',"+dto.SOLUONGMH+",'"+dto.HANSUDUNG+"',"+dto.GIAMUA+","+dto.GIABAN+",'"+ dto.MOTA+"','"+dto.TINHTRANG+"')";
            executeNonQuery(SQL);
        }
        public void insertNhomHang(clDTO dto)
        {
            String SQL = "insert into NHOMHANG(MANH,TENNHOMHANG,GHICHU)"
            +" values('"+dto.MANH +"','"+ dto.TENNHOMHANG +"','"+ dto.GHICHU+"')";
            executeNonQuery(SQL);
        }
        public void updateThonTinCongTy(clDTO dto)
        {
            String SQL = "update THONGTINCT set MACT= '" + dto.MACT + "',VERSION=" + dto.VERSION + ",TENCT= N'" + dto.TENCT + "',DIACHI= N'" + dto.DIACHI + "',SDT= '" + dto.SDT + "',"
            + " MOBILE= '" + dto.MOBILE + "',EMAIL= '" + dto.EMAIL + "',FAX= '" + dto.FAX + "',MASOTHUE= '" + dto.MASOTHUE + "',WEBSITE= '" + dto.WEBSITE + "',TTINTRAI= N'" + dto.TTINTRAI + "',TTINPHAI= N'" + dto.TTINPHAI + "',TTINGIUA= N'" + dto.TTINGIUA + "'   "
            +" where 	(MACT='"+dto.MACT+"')";
            executeNonQuery(SQL);
        }//----------------GET NHAN VIEN
        public DataTable getNhanVien()
        {
            String SQL = "select MANV,MABP,USERNAMES  AS USERNAME,PASSWORD,CHUCVU,TENNV,DIACHI,NGAYSINH,SCMND,SDT,TINHTRANG from  NHANVIEN where TINHTRANG='False'";
            return getdata(SQL);
        }

        public DataTable getNhanVienBP(clDTO dto)
        {
            String SQL = "select MANV,MABP,USERNAMES  AS USERNAME,PASSWORD,CHUCVU,TENNV,DIACHI,NGAYSINH,SCMND,SDT,TINHTRANG from NHANVIEN where mabp='"+dto.MABOPHAN+"' and TINHTRANG='True'";
            return getdata(SQL);

        }
        public DataTable getBoPhan()
        {
            String SQL = "select MABP,TENBOPHAN,TINHTRANG,ISEDITTODAY from  BOPHAN";
            return getdata(SQL);
        }
        public DataTable getThongTinCT(clDTO dto)
        {
            String SQL = "select * from  THONGTINCT where (MACT='"+dto.MACT+"')";
            return getdata(SQL);
        }
        public void delMatHang(clDTO dto)
        {
            String SQL = "delete MATHANG where 	(MAMH='"+dto.MAMH+"')";
            executeNonQuery(SQL);
        }
        //-------------------------THEM NGUOI DUNG --

        public void THEMNGUOIDUNG(clDTO dto)
        {
            String SQL = "update NHANVIEN set MABP= '" + dto.MABOPHAN + "',USERNAMES= '" + dto.TENDANGNHAP + "',PASSWORD= '" + dto.MATKHAU + "',TINHTRANG='" + dto.TINHTRANG + "' where MANV='" + dto.MANV + "'";
            executeNonQuery(SQL);
        }
          public void SuaNguoiDung(clDTO dto)
        {
            String SQL = "update NHANVIEN set MABP= '" + dto.MABOPHAN + "' where MANV='" + dto.MANV + "'";
            executeNonQuery(SQL);
        }
          public void DoiMatKhau(clDTO dto)
          {
              String SQL = "update NHANVIEN set PASSWORD='" + dto.MATKHAU + "' where 	MANV='" + dto.MANV + "'";
              executeNonQuery(SQL);
          }
          public DataTable KiemTraMatKhau(clDTO dto)
          {
              String SQL = "select * from NHANVIEN where MANV='" + dto.MANV + "' AND PASSWORD='" + dto.MATKHAU + "'";
              return getdata(SQL);

          }
        public void XoaNguoiDUng(clDTO dto)
        {
            String SQL = "update NHANVIEN set MABP=null,USERNAMES=null,PASSWORD=null,TINHTRANG= 'False' where 	MANV='" + dto.MANV + "'";
            executeNonQuery(SQL);
        }
        public DataTable getNhomHang()
        {
            String SQL = "select MANH,TENNHOMHANG,GHICHU from  NHOMHANG";
            return getdata(SQL);
        }
        //------------------Get all Kho-------------------
        public DataTable getKho()
        {
            String SQL = "select 	MAKHO,MANV,TENKHO,DIACHI,SDTB,DTDD,NGUOILH,FAX,GHICHU,TINHTRANG from  KHO";
            return getdata(SQL);
        }
        //------------------------TON KHO
        public DataTable getTonKhoTTngay2(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MAMH != "" && dto.MAMH != null)
            {
                SQL1 = " AND MATHANG.MAMH='" + dto.MAMH + "'  ";
            }
            if (dto.MANCC != "" && dto.MANCC != null)
            {
                SQL1 = SQL1 + " AND MATHANG.MANCC='" + dto.MANCC + "'  ";
            }
            string TYPE = "";
            
            string TYPEEND = "";
            TYPEEND = "AND (TONDAU+NHAP+TRANHAP+XUAT+TRAXUAT>0 OR(SOLUONGMH=0 AND LOHANG='" + PublicVariable.LOHANG + "'))";
            if (PublicVariable.isHSD)
            {
                TYPE = " SELECT  TENMH,MAMH,GIAMUA,MANCC,TENNCC,KLDVT,DONVITINH,NGAY,SUM(TONTT) AS TONTT, SUM(CHENHLECH) AS CHENHLECH, SUM (TONDAU) AS TONDAU, SUM (KLTONDAU) AS KLTONDAU,SUM(THANHTIENTONDAU) AS THANHTIENTONDAU, SUM(NHAP) AS NHAP, SUM(KLNHAP) AS KLNHAP,SUM(THANHTIENNHAP) AS THANHTIENNHAP, SUM(XUAT) AS XUAT,SUM(KLXUAT) AS KLXUAT,SUM(THANHTIENXUAT) AS THANHTIENXUAT,SUM(TRANHAP) AS TRANHAP, SUM(KLTRANHAP) AS KLTRANHAP, SUM(THANHTIENTRANHAP) AS THANHTIENTRANHAP, SUM(TRAXUAT) AS TRAXUAT, SUM(KLTRAXUAT) AS KLTRAXUAT, SUM(THANHTIENTRAXUAT) AS THANHTIENTRAXUAT,SUM(TONCUOI) AS TONCUOI, SUM(KLTONCUOI) AS KLTONCUOI, SUM(THANHTIENTONCUOI) AS THANHTIENTONCUOI FROM( ";

                TYPEEND = TYPEEND + " ) AS T22   GROUP BY TENMH,MAMH,GIAMUA,MANCC,TENNCC,KLDVT,DONVITINH,NGAY"; ;
            }
            if (dto.ISFILTER)
            {
                if (!PublicVariable.isTONNHAPXUATNGAYFULL)
                {
                    TYPE = "SELECT * FROM ( " + TYPE;
                    TYPEEND = TYPEEND + " ) AS T33 WHERE NHAP+TRANHAP+XUAT+TRAXUAT>0";
                }
            }
            String SQL = TYPE + "SELECT TENMH+' - ' + QUYCACH AS TENMH,convert(varchar,HSD,103) AS HSD,MATHANG.MAMH,MATHANG.GIAMUA,LOHANG, MATHANG.MANCC, TENNCC,KLDVT, DONVITINH,convert(varchar,GETDATE(),103) AS NGAY, TONCUOI AS TONTT, TONCUOI-TONCUOI AS CHENHLECH, TONDAU, TONDAU*KLDVT AS KLTONDAU, TONDAU*T1.GIAMUA AS THANHTIENTONDAU, NHAP, NHAP*KLDVT AS KLNHAP, THANHTIENNHAP, XUAT, XUAT*KLDVT AS KLXUAT, THANHTIENXUAT, TRANHAP, TRANHAP*KLDVT AS KLTRANHAP, THANHTIENTRANHAP, TRAXUAT, TRAXUAT*KLDVT AS KLTRAXUAT, THANHTIENTRAXUAT, TONCUOI, TONCUOI*KLDVT AS KLTONCUOI, TONCUOI*T1.GIAMUA AS THANHTIENTONCUOI FROM"
            +" (SELECT HSD,KHOHANG.MAMH,KHOHANG.LOHANG,GIAMUA,(KHOHANG.TONKHO -(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) )AS TONDAU,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "') AS NHAP,"
            + " (SELECT  SUM(GIATIEN)   FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS THANHTIENNHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS XUAT,"
            + " (SELECT  SUM(GIATIEN)   FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS THANHTIENXUAT,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS TRANHAP,"
            + " (SELECT  SUM(GIATIEN)   FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS THANHTIENTRANHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS TRAXUAT,"
            + " (SELECT  SUM(GIATIEN)   FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS THANHTIENTRAXUAT,KHOHANG.TONKHO AS TONCUOI FROM KHOHANG) AS T1, MATHANG,NHACUNGCAP, DONVITINH WHERE MATHANG.TINHTRANG='True' AND MATHANG.MAMH=T1.MAMH AND NHACUNGCAP.MANCC=MATHANG.MANCC AND MATHANG.MADVT = DONVITINH.MADVT AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' " + SQL1 + TYPEEND;

            return getdata(SQL);
        }

        public DataTable getTonKhoTTngay(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MAMH != "" && dto.MAMH != null)
            {
                SQL1 = " AND MATHANG.MAMH='" + dto.MAMH + "'  ";
            }
            if (dto.MANCC != "" && dto.MANCC != null)
            {
                SQL1 = SQL1 + " AND MATHANG.MANCC='" + dto.MANCC + "'  ";
            }
            string TYPE = "";
            string TYPEEND = "";
            string TYPEEND2 = "";

            if (dto.ISFILTER)
            {
                if (PublicVariable.isTONNHAPXUATNGAYFULL)
                {
                    if (PublicVariable.isHSD)
                    {
                        TYPE = "SELECT * FROM( " + TYPE;
                        TYPEEND2 = ") AS T333 WHERE TONDAU+NHAP+TRANHAP+XUAT+TRAXUAT>0 ";
                    }
                    else
                    {
                        TYPE = "";
                        TYPEEND = "AND TONDAU+NHAP+TRANHAP+XUAT+TRAXUAT>0 ";
                    }
                }
                else
                {
                    if (PublicVariable.isHSD)
                    {
                        TYPE = "SELECT * FROM( " + TYPE;
                        TYPEEND2 = ") AS T333 WHERE NHAP+TRANHAP+XUAT+TRAXUAT>0 ";
                    }
                    else
                    {
                        TYPE = "";
                        TYPEEND = "AND NHAP+TRANHAP+XUAT+TRAXUAT>0 ";
                    }
                }
            }
            else
            {
                TYPEEND = "AND TONDAU+NHAP+TRANHAP+XUAT+TRAXUAT>0 ";
            }

            String SQL="";
            if (PublicVariable.isHSD)
            {
              /*  SQL = TYPE + "SELECT  TENMH,TONKHOTT.MAMH,GIAMUA,MANCC,TENNCC,KLDVT,DONVITINH,convert(varchar,TONKHOTT.NGAY,103) AS NGAY ,TONKHONGAY as TONTT, TONKHONGAY-SUM(TONCUOI) AS CHENHLECH, SUM (TONDAU) AS TONDAU, SUM (KLTONDAU) AS KLTONDAU,SUM(THANHTIENTONDAU) AS THANHTIENTONDAU, SUM(NHAP) AS NHAP, SUM(KLNHAP) AS KLNHAP,SUM(THANHTIENNHAP) AS THANHTIENNHAP, SUM(XUAT) AS XUAT,SUM(KLXUAT) AS KLXUAT,SUM(THANHTIENXUAT) AS THANHTIENXUAT,SUM(TRANHAP) AS TRANHAP, SUM(KLTRANHAP) AS KLTRANHAP, SUM(THANHTIENTRANHAP) AS THANHTIENTRANHAP, SUM(TRAXUAT) AS TRAXUAT, SUM(KLTRAXUAT) AS KLTRAXUAT, SUM(THANHTIENTRAXUAT) AS THANHTIENTRAXUAT,SUM(TONCUOI) AS TONCUOI, SUM(KLTONCUOI) AS KLTONCUOI, SUM(THANHTIENTONCUOI) AS THANHTIENTONCUOI FROM( "
                + " SELECT TENMH+' - ' + QUYCACH AS TENMH,MATHANG.MAMH,MATHANG.GIAMUA, MATHANG.MANCC, TENNCC,KLDVT, DONVITINH,convert(varchar,GETDATE(),103) AS NGAY, TONDAU, TONDAU*KLDVT AS KLTONDAU, TONDAU*T1.GIAMUA AS THANHTIENTONDAU, NHAP, NHAP*KLDVT AS KLNHAP, THANHTIENNHAP, XUAT, XUAT*KLDVT AS KLXUAT, THANHTIENXUAT, TRANHAP, TRANHAP*KLDVT AS KLTRANHAP, THANHTIENTRANHAP, TRAXUAT, TRAXUAT*KLDVT AS KLTRAXUAT, THANHTIENTRAXUAT, TONCUOI, TONCUOI*KLDVT AS KLTONCUOI, TONCUOI*T1.GIAMUA AS THANHTIENTONCUOI FROM"
                + " (SELECT KHOHANG.MAMH,KHOHANG.GIAMUA,"
                + " (SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH  AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG)+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY < '" + dto.NGAYBDKHO + "' ) AS TONDAU, "
                + " (SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "') AS NHAP,"
                + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) AS THANHTIENNHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  = '" + dto.NGAYBDKHO + "') AS XUAT,"
                + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) AS THANHTIENXUAT,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  = '" + dto.NGAYBDKHO + "') AS TRANHAP,"
                + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) AS THANHTIENTRANHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  = '" + dto.NGAYBDKHO + "') AS TRAXUAT,"
                + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) AS THANHTIENTRAXUAT,(SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH   AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG )+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY <= '" + dto.NGAYBDKHO + "' ) AS TONCUOI"
                + " FROM (SELECT KHOHANG.MAMH,TONKHO,GIAMUA,LOHANG FROM KHOHANG ) AS KHOHANG) AS T1, MATHANG,NHACUNGCAP, DONVITINH WHERE MATHANG.TINHTRANG='True' AND MATHANG.MAMH=T1.MAMH AND NHACUNGCAP.MANCC=MATHANG.MANCC AND MATHANG.MADVT = DONVITINH.MADVT AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' " + SQL1 + ") AS T22, TONKHOTT WHERE TONKHOTT.MAMH=T22.MAMH AND TONKHOTT.NGAY='" + dto.NGAYBDKHO + "' "+TYPEEND+"   GROUP BY TENMH,TONKHOTT.MAMH,GIAMUA,MANCC,TENNCC,KLDVT,DONVITINH,TONKHOTT.NGAY,TONKHOTT.TONKHONGAY " + TYPEEND2;
*/
                SQL = TYPE + "SELECT TENMH+' - ' + QUYCACH AS TENMH,MATHANG.MAMH,GIAMUA,MATHANG.MANCC,TENNCC,KLDVT,DONVITINH,convert(varchar,TONKHOTT.NGAY,103) AS NGAY ,TONKHONGAY as TONTT, TONKHONGAY-TONCUOI AS CHENHLECH,  TONDAU, TONDAU*KLDVT AS KLTONDAU,TONDAU*GIAMUA AS THANHTIENTONDAU,  NHAP, NHAP*KLDVT AS KLNHAP,GIANHAP AS THANHTIENNHAP,  XUAT,XUAT*KLDVT KLXUAT,GIAXUAT AS THANHTIENXUAT, TRANHAP,TRANHAP*KLDVT AS KLTRANHAP, GIATRANHAP AS THANHTIENTRANHAP,  TRAXUAT, TRAXUAT*KLDVT AS KLTRAXUAT, GIATRAXUAT AS THANHTIENTRAXUAT,TONCUOI, TONCUOI*KLDVT AS KLTONCUOI, TONCUOI*GIAMUA AS THANHTIENTONCUOI FROM( "
                + " SELECT TONDAU,TONDAU+ISNULL(NHAP,0)+ISNULL(XUAT,0)+ISNULL(TRANHAP,0)+ISNULL(TRAXUAT,0) AS TONCUOI,ISNULL(NHAP,0)AS NHAP,ISNULL(GIANHAP,0)AS GIANHAP,-ISNULL(XUAT,0)AS XUAT,ISNULL(GIAXUAT,0)AS GIAXUAT,-ISNULL(TRANHAP,0)AS TRANHAP,ISNULL(GIATRANHAP,0)AS GIATRANHAP,ISNULL(TRAXUAT,0)AS TRAXUAT,ISNULL(GIATRAXUAT,0)AS GIATRAXUAT,T1.MAMH FROM "
                + " (SELECT T11.MAMH, ISNULL(NHAPXUAT,0)+TONKHO AS TONDAU FROM (SELECT SUM(NHAPXUAT)AS NHAPXUAT,MATHANG.MAMH FROM TONKHO,MATHANG WHERE TONKHO.MAMH=MATHANG.MAMH AND TONKHO.NGAY < '" + dto.NGAYBDKHO + "' AND TONKHO.MAKHO='" + PublicVariable.MAKHO + "'  GROUP BY MATHANG.MAMH) AS T11, (SELECT SUM(TONKHO) AS TONKHO,MATHANG.MAMH  FROM TONDAUKHOHANG,MATHANG WHERE TONDAUKHOHANG.MAMH=MATHANG.MAMH AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' GROUP BY MATHANG.MAMH) AS T22 WHERE T11.MAMH=T22.MAMH)  AS T1"
                + " FULL OUTER JOIN"
                + " (SELECT MAMH,sum(CASE WHEN MANHAPXUAT='N' THEN NHAPXUAT ELSE 0 end) As NHAP,sum(CASE WHEN MANHAPXUAT='N' THEN GIATIEN ELSE 0 end) As GIANHAP,sum(CASE WHEN MANHAPXUAT='X' THEN NHAPXUAT ELSE 0 end) As XUAT,sum(CASE WHEN MANHAPXUAT='X' THEN GIATIEN ELSE 0 end) As GIAXUAT,sum(CASE WHEN MANHAPXUAT='TN' THEN NHAPXUAT ELSE 0 end) As TRANHAP,sum(CASE WHEN MANHAPXUAT='TN' THEN GIATIEN ELSE 0 end) As GIATRANHAP,sum(CASE WHEN MANHAPXUAT='TX' THEN NHAPXUAT ELSE 0 end) As TRAXUAT,sum(CASE WHEN MANHAPXUAT='TX' THEN GIATIEN ELSE 0 end) As GIATRAXUAT"
                + " FROM TONKHO WHERE TONKHO.NGAY='" + dto.NGAYBDKHO + "' AND TONKHO.MAKHO='" + PublicVariable.MAKHO + "' GROUP BY MAMH)AS T2 ON T1.MAMH=T2.MAMH) AS T3,(SELECT MAMH,NGAY,TONKHONGAY FROM TONKHOTT WHERE TONKHOTT.MAKHO='" + PublicVariable.MAKHO + "' AND TONKHOTT.NGAY='" + dto.NGAYBDKHO + "') AS TONKHOTT,MATHANG,NHACUNGCAP,DONVITINH "
                + " WHERE T3.MAMH=MATHANG.MAMH AND MATHANG.MANCC=NHACUNGCAP.MANCC AND MATHANG.MAMH=TONKHOTT.MAMH AND MATHANG.MADVT=DONVITINH.MADVT AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' " + SQL1  + TYPEEND2;
            }
            else
            {/*
                SQL = TYPE + " SELECT TENMH+' - ' + QUYCACH AS TENMH,MATHANG.MAMH,MATHANG.GIAMUA, MATHANG.MANCC, TENNCC,KLDVT, DONVITINH,convert(varchar,NGAY,103) AS NGAY,TONTT, TONTT-TONCUOI AS CHENHLECH, TONDAU, TONDAU*KLDVT AS KLTONDAU, TONDAU*T1.GIAMUA AS THANHTIENTONDAU, NHAP, NHAP*KLDVT AS KLNHAP, THANHTIENNHAP, XUAT, XUAT*KLDVT AS KLXUAT, THANHTIENXUAT, TRANHAP, TRANHAP*KLDVT AS KLTRANHAP, THANHTIENTRANHAP, TRAXUAT, TRAXUAT*KLDVT AS KLTRAXUAT, THANHTIENTRAXUAT, TONCUOI, TONCUOI*KLDVT AS KLTONCUOI, TONCUOI*T1.GIAMUA AS THANHTIENTONCUOI FROM"
                + " (SELECT KHOHANG.MAMH,KHOHANG.GIAMUA,TONTT,NGAY,"
                + " (SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH  AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG)+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY < '" + dto.NGAYBDKHO + "' ) AS TONDAU, "
                + " (SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "') AS NHAP,"
                + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) AS THANHTIENNHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  = '" + dto.NGAYBDKHO + "') AS XUAT,"
                + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) AS THANHTIENXUAT,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  = '" + dto.NGAYBDKHO + "') AS TRANHAP,"
                + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) AS THANHTIENTRANHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  = '" + dto.NGAYBDKHO + "') AS TRAXUAT,"
                + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) AS THANHTIENTRAXUAT,(SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH   AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG )+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY <= '" + dto.NGAYBDKHO + "' ) AS TONCUOI"
                + " FROM (SELECT KHOHANG.MAMH,TONKHO,GIAMUA,TONKHONGAY AS TONTT,LOHANG,TONKHOTT.NGAY FROM KHOHANG,TONKHOTT WHERE KHOHANG.MAMH=TONKHOTT.MAMH AND TONKHOTT.MAKHO='" + PublicVariable.MAKHO + "' AND TONKHOTT.NGAY='" + dto.NGAYBDKHO + "') AS KHOHANG ) AS T1, MATHANG,NHACUNGCAP, DONVITINH WHERE MATHANG.TINHTRANG='True' AND MATHANG.MAMH=T1.MAMH AND NHACUNGCAP.MANCC=MATHANG.MANCC AND MATHANG.MADVT = DONVITINH.MADVT AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' " + SQL1 + TYPEEND;
                */
                SQL = TYPE + "SELECT TENMH+' - ' + QUYCACH AS TENMH,MATHANG.MAMH,GIAMUA,MATHANG.MANCC,TENNCC,KLDVT,DONVITINH,convert(varchar,TONKHOTT.NGAY,103) AS NGAY ,TONKHONGAY as TONTT, TONKHONGAY-TONCUOI AS CHENHLECH,  TONDAU, TONDAU*KLDVT AS KLTONDAU,TONDAU*GIAMUA AS THANHTIENTONDAU,  NHAP, NHAP*KLDVT AS KLNHAP,GIANHAP AS THANHTIENNHAP,  XUAT,XUAT*KLDVT KLXUAT,GIAXUAT AS THANHTIENXUAT, TRANHAP,TRANHAP*KLDVT AS KLTRANHAP, GIATRANHAP AS THANHTIENTRANHAP,  TRAXUAT, TRAXUAT*KLDVT AS KLTRAXUAT, GIATRAXUAT AS THANHTIENTRAXUAT,TONCUOI, TONCUOI*KLDVT AS KLTONCUOI, TONCUOI*GIAMUA AS THANHTIENTONCUOI FROM( "
                + " SELECT TONDAU,TONDAU+ISNULL(NHAP,0)+ISNULL(XUAT,0)+ISNULL(TRANHAP,0)+ISNULL(TRAXUAT,0) AS TONCUOI,ISNULL(NHAP,0)AS NHAP,ISNULL(GIANHAP,0)AS GIANHAP,-ISNULL(XUAT,0)AS XUAT,ISNULL(GIAXUAT,0)AS GIAXUAT,-ISNULL(TRANHAP,0)AS TRANHAP,ISNULL(GIATRANHAP,0)AS GIATRANHAP,ISNULL(TRAXUAT,0)AS TRAXUAT,ISNULL(GIATRAXUAT,0)AS GIATRAXUAT,T1.MAMH FROM "
                + " (SELECT T11.MAMH, ISNULL(NHAPXUAT,0)+TONKHO AS TONDAU FROM (SELECT SUM(NHAPXUAT)AS NHAPXUAT,MATHANG.MAMH FROM TONKHO,MATHANG WHERE TONKHO.MAMH=MATHANG.MAMH AND TONKHO.NGAY < '" + dto.NGAYBDKHO + "' AND TONKHO.MAKHO='" + PublicVariable.MAKHO + "'  GROUP BY MATHANG.MAMH) AS T11, (SELECT SUM(TONKHO) AS TONKHO,MATHANG.MAMH  FROM TONDAUKHOHANG,MATHANG WHERE TONDAUKHOHANG.MAMH=MATHANG.MAMH AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' GROUP BY MATHANG.MAMH) AS T22 WHERE T11.MAMH=T22.MAMH)  AS T1"
                + " FULL OUTER JOIN"
                + " (SELECT MAMH,sum(CASE WHEN MANHAPXUAT='N' THEN NHAPXUAT ELSE 0 end) As NHAP,sum(CASE WHEN MANHAPXUAT='N' THEN GIATIEN ELSE 0 end) As GIANHAP,sum(CASE WHEN MANHAPXUAT='X' THEN NHAPXUAT ELSE 0 end) As XUAT,sum(CASE WHEN MANHAPXUAT='X' THEN GIATIEN ELSE 0 end) As GIAXUAT,sum(CASE WHEN MANHAPXUAT='TN' THEN NHAPXUAT ELSE 0 end) As TRANHAP,sum(CASE WHEN MANHAPXUAT='TN' THEN GIATIEN ELSE 0 end) As GIATRANHAP,sum(CASE WHEN MANHAPXUAT='TX' THEN NHAPXUAT ELSE 0 end) As TRAXUAT,sum(CASE WHEN MANHAPXUAT='TX' THEN GIATIEN ELSE 0 end) As GIATRAXUAT"
                + " FROM TONKHO WHERE TONKHO.NGAY='" + dto.NGAYBDKHO + "' AND TONKHO.MAKHO='" + PublicVariable.MAKHO + "' GROUP BY MAMH)AS T2 ON T1.MAMH=T2.MAMH) AS T3,(SELECT MAMH,NGAY,TONKHONGAY FROM TONKHOTT WHERE TONKHOTT.MAKHO='" + PublicVariable.MAKHO + "' AND TONKHOTT.NGAY='" + dto.NGAYBDKHO + "') AS TONKHOTT,MATHANG,NHACUNGCAP,DONVITINH "
                + " WHERE T3.MAMH=MATHANG.MAMH AND MATHANG.MANCC=NHACUNGCAP.MANCC AND MATHANG.MAMH=TONKHOTT.MAMH AND MATHANG.MADVT=DONVITINH.MADVT AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' " + SQL1 + TYPEEND2;
            }
            return getdata(SQL);
        }

        public DataTable getTonKho(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MAMH != "" && dto.MAMH != null)
            {
                SQL1 = " AND MATHANG.MAMH='" + dto.MAMH + "'  ";
            }
            if (dto.MANCC != "" && dto.MANCC != null)
            {
                SQL1 =SQL1+ " AND MATHANG.MANCC='" + dto.MANCC + "'  ";
            }
            SQL1 = SQL1 + " AND (TONDAU+NHAP+TRANHAP+XUAT+TRAXUAT>0 OR (SOLUONGMH=0 AND LOHANG='" + PublicVariable.LOHANG + "'))";
            
           // String SQL = "SELECT *, TONDAU*KLDVT AS KLTONDAU, NHAP*KLDVT AS KLNHAP,TRANHAP*KLDVT AS KLTRANHAP, XUAT*KLDVT AS KLXUAT, TRAXUAT*KLDVT AS KLTRAXUAT,TONCUOI*KLDVT AS KLTONCUOI ,TONDAU*GIABAN AS THANHTIENTONDAU, NHAP*GIABAN AS THANHTIENNHAP,TRANHAP*GIABAN AS THANHTIENTRANHAP, XUAT*GIABAN AS THANHTIENXUAT, TRAXUAT*GIABAN AS THANHTIENTRAXUAT, TONCUOI*GIABAN AS THANHTIENTONCUOI"
          //  + " FROM(SELECT T3.*,TONKHONGAY AS TONCUOI, (TONKHONGAY-(NHAP-TRANHAP-XUAT+TRAXUAT)) AS TONDAU FROM (select MAMH,TENMH,TENNCC,KLDVT,DONVITINH,GIAMUA,GIABAN,CASE WHEN NHAP IS NULL THEN 0 ELSE NHAP END AS NHAP ,CASE WHEN TRANHAP IS NULL THEN 0 ELSE TRANHAP END AS TRANHAP ,CASE WHEN XUAT IS NULL THEN 0 ELSE XUAT END AS XUAT ,CASE WHEN TRAXUAT IS NULL THEN 0 ELSE TRAXUAT END AS TRAXUAT "
        //    + " FROM (select t1.*,SUM(nhap) AS NHAP,SUM(tranhap) AS TRANHAP,SUM(xuat) AS XUAT,SUM(traxuat) AS TRAXUAT from (select mathang.mamh,tenmh,TENNCC,KLDVT,DONVITINH,GIAMUA,GIABAN from mathang,DONVITINH,NHACUNGCAP WHERE MATHANG.MADVT=DONVITINH.MADVT AND MATHANG.MANCC=NHACUNGCAP.MANCC " + SQL1 + " AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' )  as t1 LEFT JOIN (SELECT * FROM TONKHO WHERE TONKHO.MAKHO='" + PublicVariable.MAKHO + "' AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "' ) AS tonkho on tonkho.mamh= t1.mamh GROUP BY T1.MAMH, T1.TENMH, T1.TENNCC,T1.KLDVT,T1.DONVITINH, T1.GIAMUA, T1.GIABAN ) AS T2) AS T3, (SELECT * FROM TONKHOTT WHERE NGAY='" + dto.NGAYKTKHO + "' AND MAKHO='" + PublicVariable.MAKHO + "') AS TONKHOTT WHERE T3.MAMH=TONKHOTT.MAMH) AS T6";
            String SQL = " SELECT T1.MAMH,convert(varchar,HSD,103) AS HSD,t1.LOHANG,T1.GIAMUA, TONDAU,NHAP,TRANHAP,XUAT,TRAXUAT,TONCUOI,KLDVT,TENMH+' - ' + QUYCACH AS  TENMH,TENNCC,DONVITINH,TONDAU*KLDVT AS KLTONDAU,NHAP*KLDVT AS KLNHAP,TRANHAP*KLDVT AS KLTRANHAP,XUAT*KLDVT AS KLXUAT,TRAXUAT*KLDVT AS KLTRAXUAT,TONCUOI*KLDVT AS KLTONCUOI,T1.GIAMUA* TONDAU AS THANHTIENTONDAU, T1.GIAMUA*TONCUOI AS THANHTIENTONCUOI,THANHTIENNHAP,THANHTIENXUAT,THANHTIENTRANHAP,THANHTIENTRAXUAT FROM"
            + " (SELECT HSD,KHOHANG.MAMH,KHOHANG.LOHANG,KHOHANG.GIAMUA,(SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH  AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG)+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY < '" + dto.NGAYBDKHO + "' ) AS TONDAU,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS NHAP,"
            + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENNHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS XUAT,"
            + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENXUAT,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS TRANHAP,"
            + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENTRANHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS TRAXUAT,"
            + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENTRAXUAT,(SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH   AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG )+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY <= '" + dto.NGAYKTKHO + "' ) AS TONCUOI"
            + " FROM (SELECT KHOHANG.*,SOLUONGMH FROM KHOHANG, MATHANG WHERE MATHANG.TINHTRANG='True' AND MATHANG.MAMH=KHOHANG.MAMH AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "') AS KHOHANG ) AS T1, MATHANG, NHACUNGCAP,DONVITINH WHERE MATHANG.MAMH=T1.MAMH AND NHACUNGCAP.MANCC=MATHANG.MANCC AND DONVITINH.MADVT=MATHANG.MADVT AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' " + SQL1;
            // + " (SELECT KHOHANG.MAMH,KHOHANG.LOHANG,GIAMUA,(KHOHANG.TONKHO -(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "' ) )AS TONDAU,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY = '" + dto.NGAYBDKHO + "') AS NHAP,"
            //+ " (SELECT  SUM(NHAPXUAT)   FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "')*KHOHANG.GIAMUA AS THANHTIENNHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS XUAT,"
            //+ " (SELECT  -SUM(NHAPXUAT)   FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "')*KHOHANG.GIAMUA AS THANHTIENXUAT,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS TRANHAP,"
            //+ " (SELECT  -SUM(NHAPXUAT)   FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "')*KHOHANG.GIAMUA AS THANHTIENTRANHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "') AS TRAXUAT,"
            //+ " (SELECT  SUM(NHAPXUAT)   FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY ='" + dto.NGAYBDKHO + "')*KHOHANG.GIAMUA AS THANHTIENTRAXUAT,KHOHANG.TONKHO AS TONCUOI FROM KHOHANG) AS T1, MATHANG,NHACUNGCAP, DONVITINH WHERE MATHANG.MAMH=T1.MAMH AND NHACUNGCAP.MANCC=MATHANG.MANCC AND MATHANG.MADVT = DONVITINH.MADVT AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' " + SQL1;

            return getdata(SQL);
        }
        public DataTable getTonKhoncc(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MANCC != "" && dto.MANCC != null)
            {
                SQL1 = SQL1 + " AND MATHANG.MANCC='" + dto.MANCC + "'  ";
            }

            String SQL = " SELECT MANCC,TENNCC, SUM(TONDAU) AS TONDAU,SUM(NHAP) AS NHAP,SUM(XUAT) AS XUAT,SUM(TRANHAP) AS TRANHAP,SUM(TRAXUAT) AS TRAXUAT,SUM(TONCUOI) AS TONCUOI,SUM(KLTONDAU) AS KLTONDAU,SUM(KLNHAP) AS KLNHAP,SUM(KLXUAT) AS KLXUAT,SUM(KLTRANHAP) AS KLTRANHAP,SUM(KLTRAXUAT) AS KLTRAXUAT,SUM(KLTONCUOI) AS KLTONCUOI, SUM(THANHTIENTONDAU) AS THANHTIENTONDAU,SUM(THANHTIENNHAP) AS THANHTIENNHAP,SUM(THANHTIENXUAT) AS THANHTIENXUAT,SUM(THANHTIENTRANHAP) AS THANHTIENTRANHAP,SUM(THANHTIENTRAXUAT) AS THANHTIENTRAXUAT,SUM(THANHTIENTONCUOI) AS THANHTIENTONCUOI FROM ("
             + " SELECT T1.MAMH,t1.LOHANG,T1.GIAMUA, TONDAU,NHAP,TRANHAP,XUAT,TRAXUAT,TONCUOI,KLDVT, TENMH,NHACUNGCAP.MANCC,TENNCC,DONVITINH,TONDAU*KLDVT AS KLTONDAU,NHAP*KLDVT AS KLNHAP,TRANHAP*KLDVT AS KLTRANHAP,XUAT*KLDVT AS KLXUAT,TRAXUAT*KLDVT AS KLTRAXUAT,TONCUOI*KLDVT AS KLTONCUOI,T1.GIAMUA* TONDAU AS THANHTIENTONDAU, T1.GIAMUA*TONCUOI AS THANHTIENTONCUOI,THANHTIENNHAP,THANHTIENXUAT,THANHTIENTRANHAP,THANHTIENTRAXUAT FROM"
             + " (SELECT KHOHANG.MAMH,KHOHANG.LOHANG,KHOHANG.GIAMUA,(SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH  AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG)+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY < '" + dto.NGAYBDKHO + "' ) AS TONDAU,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS NHAP,"
             + " (SELECT CASE WHEN SUM(GIATIEN1) IS NULL THEN 0 ELSE SUM(GIATIEN1) END  FROM (SELECT TONKHO.*,CHITIETHDN.GIANHAP*CHITIETHDN.SOLUONGNHAP AS GIATIEN1 FROM TONKHO,CHITIETHDN WHERE  CHITIETHDN.MAHDN=TONKHO.MAHD AND CHITIETHDN.LOHANG=TONKHO.LOHANG AND CHITIETHDN.MAMH=TONKHO.MAMH AND TONKHO.TYPE='1' AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "')AS  TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENNHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS XUAT,"
             + " (SELECT CASE WHEN SUM(GIATIEN1) IS NULL THEN 0 ELSE SUM(GIATIEN1) END  FROM (SELECT TONKHO.*,CHITIETHDX.GIABAN*CHITIETHDX.SOLUONGXUAT AS GIATIEN1 FROM TONKHO,CHITIETHDX WHERE  CHITIETHDX.MAHDX=TONKHO.MAHD AND CHITIETHDX.LOHANG=TONKHO.LOHANG AND CHITIETHDX.MAMH=TONKHO.MAMH AND TONKHO.TYPE='1' AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "')AS TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENXUAT,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS TRANHAP,"
             + " (SELECT CASE WHEN SUM(GIATIEN1) IS NULL THEN 0 ELSE SUM(GIATIEN1) END  FROM (SELECT TONKHO.*,TRACHITIETHDN.GIANHAP*TRACHITIETHDN.SOLUONGNHAP AS GIATIEN1 FROM TONKHO,TRACHITIETHDN WHERE  TRACHITIETHDN.MAHDN=TONKHO.MAHD AND TRACHITIETHDN.LOHANG=TONKHO.LOHANG AND TRACHITIETHDN.MAMH=TONKHO.MAMH AND TONKHO.TYPE='1' AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "')AS TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENTRANHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS TRAXUAT,"
             + " (SELECT CASE WHEN SUM(GIATIEN1) IS NULL THEN 0 ELSE SUM(GIATIEN1) END  FROM (SELECT TONKHO.*,TRACHITIETHDX.GIABAN*TRACHITIETHDX.SOLUONGXUAT AS GIATIEN1 FROM TONKHO,TRACHITIETHDX WHERE  TRACHITIETHDX.MAHDX=TONKHO.MAHD AND TRACHITIETHDX.LOHANG=TONKHO.LOHANG AND TRACHITIETHDX.MAMH=TONKHO.MAMH AND TONKHO.TYPE='1' AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "')AS TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENTRAXUAT,(SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH   AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG )+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY <= '" + dto.NGAYKTKHO + "' ) AS TONCUOI"
             + " FROM (SELECT KHOHANG.*,SOLUONGMH FROM KHOHANG, MATHANG WHERE MATHANG.TINHTRANG='True' AND MATHANG.MAMH=KHOHANG.MAMH AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "') AS KHOHANG ) AS T1, MATHANG, NHACUNGCAP,DONVITINH WHERE MATHANG.MAMH=T1.MAMH AND NHACUNGCAP.MANCC=MATHANG.MANCC AND DONVITINH.MADVT=MATHANG.MADVT AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' " + SQL1 + ") AS TB1 GROUP BY MANCC,TENNCC ";
           

            /*
             String SQL = " SELECT MANCC,TENNCC, SUM(TONDAU) AS TONDAU,SUM(NHAP) AS NHAP,SUM(XUAT) AS XUAT,SUM(TRANHAP) AS TRANHAP,SUM(TRAXUAT) AS TRAXUAT,SUM(TONCUOI) AS TONCUOI,SUM(KLTONDAU) AS KLTONDAU,SUM(KLNHAP) AS KLNHAP,SUM(KLXUAT) AS KLXUAT,SUM(KLTRANHAP) AS KLTRANHAP,SUM(KLTRAXUAT) AS KLTRAXUAT,SUM(KLTONCUOI) AS KLTONCUOI, SUM(THANHTIENTONDAU) AS THANHTIENTONDAU,SUM(THANHTIENNHAP) AS THANHTIENNHAP,SUM(THANHTIENXUAT) AS THANHTIENXUAT,SUM(THANHTIENTRANHAP) AS THANHTIENTRANHAP,SUM(THANHTIENTRAXUAT) AS THANHTIENTRAXUAT,SUM(THANHTIENTONCUOI) AS THANHTIENTONCUOI FROM ("
              + " SELECT T1.MAMH,t1.LOHANG,T1.GIAMUA, TONDAU,NHAP,TRANHAP,XUAT,TRAXUAT,TONCUOI,KLDVT, TENMH,NHACUNGCAP.MANCC,TENNCC,DONVITINH,TONDAU*KLDVT AS KLTONDAU,NHAP*KLDVT AS KLNHAP,TRANHAP*KLDVT AS KLTRANHAP,XUAT*KLDVT AS KLXUAT,TRAXUAT*KLDVT AS KLTRAXUAT,TONCUOI*KLDVT AS KLTONCUOI,T1.GIAMUA* TONDAU AS THANHTIENTONDAU, T1.GIAMUA*TONCUOI AS THANHTIENTONCUOI,THANHTIENNHAP,THANHTIENXUAT,THANHTIENTRANHAP,THANHTIENTRAXUAT FROM"
              + " (SELECT KHOHANG.MAMH,KHOHANG.LOHANG,KHOHANG.GIAMUA,(SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH  AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG)+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY < '" + dto.NGAYBDKHO + "' ) AS TONDAU,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS NHAP,"
              + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='N' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENNHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS XUAT,"
              + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='X' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENXUAT,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE -SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS TRANHAP,"
              + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TN' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENTRANHAP,(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY  BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS TRAXUAT,"
              + " (SELECT CASE WHEN SUM(GIATIEN) IS NULL THEN 0 ELSE SUM(GIATIEN) END  FROM TONKHO WHERE TONKHO.MANHAPXUAT='TX' AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.NGAY BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "') AS THANHTIENTRAXUAT,(SELECT CASE WHEN SUM(TONKHO) IS NULL THEN 0 ELSE SUM(TONKHO) END FROM TONDAUKHOHANG WHERE TONDAUKHOHANG.MAMH=KHOHANG.MAMH   AND TONDAUKHOHANG.LOHANG=KHOHANG.LOHANG )+(SELECT CASE WHEN SUM(NHAPXUAT) IS NULL THEN 0 ELSE SUM(NHAPXUAT) END FROM TONKHO WHERE TONKHO.MAMH=KHOHANG.MAMH AND TONKHO.LOHANG=KHOHANG.LOHANG AND TONKHO.NGAY <= '" + dto.NGAYKTKHO + "' ) AS TONCUOI"
              + " FROM (SELECT KHOHANG.*,SOLUONGMH FROM KHOHANG, MATHANG WHERE MATHANG.TINHTRANG='True' AND MATHANG.MAMH=KHOHANG.MAMH AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "') AS KHOHANG ) AS T1, MATHANG, NHACUNGCAP,DONVITINH WHERE MATHANG.MAMH=T1.MAMH AND NHACUNGCAP.MANCC=MATHANG.MANCC AND DONVITINH.MADVT=MATHANG.MADVT AND MATHANG.MAKHO='" + PublicVariable.MAKHO + "' " + SQL1 + ") AS TB1 GROUP BY MANCC,TENNCC ";
            */
             /* 
                 string SQL = " SELECT TENNCC,T9.* FROM ( "
                 + " SELECT MANCC,SUM(SLTNHAP) AS SLNHAP,SUM(SLNHAP*GIANHAP) AS TTNHAP,SUM(SLTXUAT) AS SLTXUAT,SUM(SLXUAT*GIAXUAT) AS TTXUAT,SUM(SLTTRANHAP) AS SLTRANHAP,SUM(SLTNHAP*GIATRANHAP)AS TTTRANHAP,SUM(SLTTRAXUAT)AS SLTRAXUAT,SUM(SLTRAXUAT*GIATRAXUAT)AS TTTRAXUAT FROM ("
                 + " select MANCC,SOLUONGNHAP AS SLNHAP,SOLUONGNHAP+KMAI AS SLTNHAP,GIANHAP, 0 AS SLXUAT,0 AS SLTXUAT,0 AS GIAXUAT,0 AS SLTRANHAP,0 AS SLTTRANHAP,0 AS GIATRANHAP,0 AS SLTRAXUAT,0 AS SLTTRAXUAT,0 AS GIATRAXUAT from CHITIETHDN,HOADONNHAP WHERE HOADONNHAP.MAHDN=CHITIETHDN.MAHDN AND HOADONNHAP.MAKHO='" + PublicVariable.MAKHO + "' AND NGAYNHAP BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "'"
                 + " UNION ALL "
                 + " select MANCC,SOLUONGXUAT AS SLXUAT,SOLUONGXUAT+KMAI AS SLTXUAT,GIABAN AS GIAXUAT ,0 AS SLNHAP,0 AS SLTNHAP,0 AS GIANHAP,0 AS SLTRANHAP,0 AS SLTTRANHAP,0 AS GIATRANHAP,0 AS SLTRAXUAT,0 AS SLTTRAXUAT,0 AS GIATRAXUAT from (SELECT SOLUONGXUAT,KMAI,MANCC,GIABAN,MAHDX FROM CHITIETHDX, MATHANG WHERE MATHANG.MAMH=CHITIETHDX.MAMH)AS CHITIETHDX1,HOADONXUAT WHERE HOADONXUAT.MAHDX=CHITIETHDX1.MAHDX AND HOADONXUAT.MAKHO='" + PublicVariable.MAKHO + "' AND NGAYXUAT BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "'"
                 + " UNION ALL "
                 + " select MANCC ,SOLUONGNHAP AS SLTRANHAP,SOLUONGNHAP+KMAI AS SLTTRANHAP,GIANHAP AS GIATRANHAP ,0 AS SLNHAP,0 AS SLTNHAP,0 AS GIANHAP,0 AS SLXUAT,0 AS SLTXUAT,0 AS GIAXUAT,0 AS SLTRAXUAT,0 AS SLTTRAXUAT,0 AS GIATRAXUAT from TRACHITIETHDN,TRAHOADONNHAP WHERE TRAHOADONNHAP.MAHDN=TRACHITIETHDN.MAHDN AND TRAHOADONNHAP.MAKHO='" + PublicVariable.MAKHO + "' AND NGAYNHAP BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "' "
                 + " UNION ALL "
                 + " select MANCC ,SOLUONGXUAT AS SLTRAXUAT,SOLUONGXUAT+KMAI AS SLTTRAXUAT,GIABAN AS GIATRAXUAT ,0 AS SLNHAP,0 AS SLTNHAP,0 AS GIANHAP,0 AS SLXUAT,0 AS SLTXUAT,0 AS GIAXUAT,0 AS SLTRANHAP,0 AS SLTTRANHAP,0 AS GIATRANHAP from (SELECT SOLUONGXUAT,KMAI,MANCC,GIABAN,MAHDX FROM TRACHITIETHDX, MATHANG WHERE MATHANG.MAMH=TRACHITIETHDX.MAMH)AS TRACHITIETHDX1,TRAHOADONXUAT WHERE TRAHOADONXUAT.MAHDX=TRACHITIETHDX1.MAHDX AND TRAHOADONXUAT.MAKHO='" + PublicVariable.MAKHO + "' AND NGAYXUAT BETWEEN '" + dto.NGAYBDKHO + "' AND '" + dto.NGAYKTKHO + "' "
                 + " UNION ALL "
                 + " SELECT MANCC,0 AS SLNHAP,0 AS SLTNHAP,0 AS GIANHAP,0 AS SLXUAT,0 AS SLTXUAT,0 AS GIAXUAT,0 AS SLTRANHAP,0 AS SLTTRANHAP,0 AS GIATRANHAP,0 AS SLTRAXUAT,0 AS SLTTRAXUAT,0 AS GIATRAXUAT FROM NHACUNGCAP WHERE  NHACUNGCAP.MAKHO='KHO1' "
                 + " ) AS T0 "
                 + " GROUP BY MANCC)AS T9, NHACUNGCAP WHERE NHACUNGCAP.MANCC=T9.MANCC ";
                  */
            return getdata(SQL);
        }
        //--------------------Backup Restore---------------------------


        public void KET_SO()
        {
            string SQLKETSO = "\r\nGO\r\n DELETE KHOHANG WHERE TONKHO=0 AND LOHANG<>'TONDAU' " +
            "\r\nGO\r\n DELETE TONDAUKHOHANG " +
            "\r\nGO\r\n INSERT INTO TONDAUKHOHANG ([MAMH],[LOHANG],[GIAMUA],[TONKHO]) SELECT MAMH,LOHANG,GIAMUA,TONKHO FROM KHOHANG  " +
            "\r\nGO\r\n DELETE TONDAUMATHANG " +
            "\r\nGO\r\n INSERT INTO TONDAUMATHANG ([MAMH],[TONDAU]) SELECT MAMH, SOLUONGMH AS TONDAU FROM MATHANG " +
            "\r\nGO\r\n DELETE TONDAUCONGNOKH " +
            "\r\nGO\r\n INSERT INTO TONDAUCONGNOKH ([MAKH],[CONGNO]) SELECT MAKH, CONGNO FROM KHACHHANG " +
            "\r\nGO\r\n DELETE TONDAUCONGNONCC " +
            "\r\nGO\r\n INSERT INTO TONDAUCONGNONCC ([MANCC],[CONGNO]) SELECT MANCC, CONGNO FROM NHACUNGCAP " +
            "\r\nGO\r\n DELETE CHITIETHDN " +
            "\r\nGO\r\n DELETE HOADONNHAP " +
            "\r\nGO\r\n DELETE CHITIETHDX " +
            "\r\nGO\r\n DELETE CHITIETHDXTAM " +
            "\r\nGO\r\n DELETE HOADONXUAT " +
            "\r\nGO\r\n DELETE TRACHITIETHDN " +
            "\r\nGO\r\n DELETE TRAHOADONNHAP " +
            "\r\nGO\r\n DELETE TRACHITIETHDX " +
            "\r\nGO\r\n DELETE TRAHOADONXUAT " +
            "\r\nGO\r\n DELETE [LOG] " +
            "\r\nGO\r\n DELETE PHIEUCHI " +
            "\r\nGO\r\n DELETE PHIEUTHU " +
            "\r\nGO\r\n DELETE TONKHO " +
            "\r\nGO\r\n DELETE TONKHOTT " +
            "\r\nGO\r\n DELETE TIENTRATRUOC " +
            "\r\nGO\r\n DELETE TONKIEMKHO ";
            try
            {
            executeNonQuery2(SQLKETSO);
            }
            catch
            {
                System.Windows.Forms.MessageBox.Show("CÓ LỖI XẢY RA RỒI KHÔNG KẾT SỔ ĐƯỢC");
            }
        }

        public  void Backup(clDTO DTO)
        {
            try
            {
                String SQL = "BACKUP DATABASE KHO_VINAVETCO TO DISK = '" + DTO.TENFILE + "'";
                executeNonQuery(SQL);
            }
            catch
            {
                System.Windows.Forms.MessageBox.Show("không backup được");
            }
        }
        public DataTable getDoanhThu(clDTO dto)
        {
            String SQL ="select  NGAYXUAT , TENKH as 'Tên Khách hàng',TENKV ,SUM(TIENPHAITRA) AS  'TongDoanhThu' FROM HOADONXUAT,KHACHHANG,KHUVUC WHERE KHUVUC.MAKV=KHACHHANG.MAKV AND KHACHHANG.MAKH=HOADONXUAT.MAKH  AND  NGAYXUAT BETWEEN '"+dto.NGAYBD+"' AND '"+dto.NGAYKT+"' group by TENKH,TENKV,ngayxuat AND HOADONXUAT.MAKHO='"+PublicVariable.MAKHO+"'";
            
            return getdata(SQL);
        }
        public DataTable getcpmuahangngay(clDTO dto)
        {
            string SQL = "SELECT NGAYNHAP, SUM(NHAP) AS NHAP, SUM(TRAXUAT) AS TRAXUAT FROM (SELECT NGAYNHAP, TIENPHAITRA AS NHAP, 0 AS TRAXUAT FROM HOADONNHAP WHERE MAKHO='" + PublicVariable.MAKHO + "' AND TYPE=1 AND NGAYNHAP BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' UNION ALL SELECT NGAYXUAT AS NGAYNHAP, 0 AS NHAP, TIENPHAITRA AS TRAXUAT FROM TRAHOADONXUAT WHERE MAKHO='" + PublicVariable.MAKHO + "'  AND TYPE=1 AND NGAYXUAT BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' ) AS T2 GROUP BY NGAYNHAP";
            return getdata(SQL);
        }

        public DataTable getcpmuahangncc(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MANCC != "" && dto.MANCC != null)
            {
                SQL1 = " AND NHACUNGCAP.MANCC='" + dto.MANCC + "'  ";
            }
            //string SQL = "SELECT MATHANG.MANCC,TENNCC,SUM(NHAP) AS TIENMUAHANG FROM (select  MAMH, SUM(GIATIEN) AS NHAP FROM TONKHO as T2 WHERE MANHAPXUAT='N' AND NGAY BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' AND T2.MAKHO='" + PublicVariable.MAKHO + "' group by MAMH) AS T3, NHACUNGCAP,MATHANG WHERE MATHANG.MANCC=NHACUNGCAP.MANCC AND T3.MAMH=MATHANG.MAMH " + SQL1 + "  group by MATHANG.MANCC,TENNCC";
            string SQL = "SELECT HOADONNHAP.MANCC,TENNCC,SUM(HOADONNHAP.TIENPHAITRA) AS TIENMUAHANG, SUM(KHOILUONG) AS KHOILUONG FROM HOADONNHAP, NHACUNGCAP ,(SELECT SUM(NHAPXUAT*KLDVT) as KHOILUONG,MAHD FROM TONKHO,MATHANG WHERE MATHANG.MAMH=TONKHO.MAMH GROUP BY MAHD) AS TONKHO WHERE TONKHO.MAHD=HOADONNHAP.MAHDN AND HOADONNHAP.MANCC=NHACUNGCAP.MANCC  AND TYPE=1 AND NGAYNHAP BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' AND HOADONNHAP.MAKHO='" + PublicVariable.MAKHO + "'   " + SQL1 + " GROUP BY HOADONNHAP.MANCC, TENNCC";
            return getdata(SQL);
        }

        public DataTable getcpmuahang_KHTRA(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MAKH != "")
            {
                SQL1 = " AND KHACHHANG.MAKH='" + dto.MAKH + "'  ";
            }
            //string SQL = "SELECT KHACHHANG.MAKH,TENKH,SUM(NHAP) AS TIENMUAHANG FROM (select  MADOITUONG, SUM(GIATIEN) AS NHAP FROM TONKHO as T2 WHERE MANHAPXUAT='TX' AND NGAY BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' AND T2.MAKHO='" + PublicVariable.MAKHO + "' group by MADOITUONG) AS T3, KHACHHANG WHERE KHACHHANG.MAKH=T3.MADOITUONG  " + SQL1 + "  group by KHACHHANG.MAKH,TENKH";
            string SQL = "SELECT KHACHHANG.MAKH,TENKH,SUM(TIENPHAITRA) AS TIENMUAHANG , SUM(KHOILUONG) AS KHOILUONG FROM TRAHOADONXUAT, KHACHHANG ,(SELECT SUM(NHAPXUAT*KLDVT) as KHOILUONG,MAHD FROM TONKHO,MATHANG WHERE MATHANG.MAMH=TONKHO.MAMH GROUP BY MAHD) AS TONKHO WHERE TONKHO.MAHD=TRAHOADONXUAT.MAHDX AND TRAHOADONXUAT.MAKH=KHACHHANG.MAKH AND NGAYXUAT BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "'  AND TYPE=1 AND TRAHOADONXUAT.MAKHO='" + PublicVariable.MAKHO + "'   " + SQL1 + " GROUP BY KHACHHANG.MAKH, TENKH";
            
            return getdata(SQL);
        }
        public DataTable getDoanhThungay(clDTO dto)
        {

            string SQL = "SELECT NGAYXUAT, SUM(XUAT) AS XUAT, SUM(TRANHAP) AS TRANHAP FROM (SELECT NGAYXUAT, TIENPHAITRA AS XUAT, 0 AS TRANHAP FROM HOADONXUAT WHERE MAKHO='" + PublicVariable.MAKHO + "'  AND TYPE=1 AND NGAYXUAT BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' UNION ALL SELECT NGAYNHAP AS NGAYXUAT, 0 AS XUAT, TIENPHAITRA AS TRANHAP FROM TRAHOADONNHAP WHERE MAKHO='" + PublicVariable.MAKHO + "'  AND TYPE=1 AND NGAYNHAP BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' ) AS T2 GROUP BY NGAYXUAT";
           
            return getdata(SQL);
        }
        public DataTable getDoanhThukh(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MAKH != "")
            {
                SQL1 = " AND KHACHHANG.MAKH='" + dto.MAKH + "'  ";
            }
            //string SQL = "SELECT KHACHHANG.MAKH,TENKH,SUM(NHAP) AS DOANHTHU,SUM(NHAPXUAT) AS KHOILUONG FROM (select  MADOITUONG, SUM(GIATIEN) AS NHAP, -SUM(NHAPXUAT) AS NHAPXUAT FROM TONKHO as T2 WHERE MANHAPXUAT='X' AND NGAY BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' AND T2.MAKHO='" + PublicVariable.MAKHO + "' group by MADOITUONG) AS T3, KHACHHANG WHERE KHACHHANG.MAKH=T3.MADOITUONG  " + SQL1 + "  group by KHACHHANG.MAKH,TENKH";
            string SQL = "SELECT KHACHHANG.MAKH,TENKH,SUM(TIENPHAITRA) AS DOANHTHU , SUM(-KHOILUONG) AS KHOILUONG FROM HOADONXUAT, KHACHHANG ,(SELECT SUM(NHAPXUAT*KLDVT) as KHOILUONG,MAHD FROM TONKHO,MATHANG WHERE MATHANG.MAMH=TONKHO.MAMH GROUP BY MAHD) AS TONKHO WHERE TONKHO.MAHD=HOADONXUAT.MAHDX AND  HOADONXUAT.MAKH=KHACHHANG.MAKH AND NGAYXUAT BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "'  AND TYPE=1 AND HOADONXUAT.MAKHO='" + PublicVariable.MAKHO + "'   " + SQL1 + " GROUP BY KHACHHANG.MAKH, TENKH";
            
            return getdata(SQL);
        }
        public DataTable getDoanhThuTRANCC(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MANCC != "" && dto.MANCC != null)
            {
                SQL1 = " AND NHACUNGCAP.MANCC='" + dto.MANCC + "'  ";
            }
            //string SQL = "SELECT MATHANG.MANCC,TENNCC,SUM(NHAP) AS DOANHTHU, SUM(KLUONG) AS KHOILUONG FROM (select  MAMH, -SUM(NHAPXUAT) AS KLUONG, SUM(GIATIEN) AS NHAP FROM TONKHO as T2 WHERE MANHAPXUAT='TN' AND NGAY BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' AND T2.MAKHO='" + PublicVariable.MAKHO + "' group by MAMH) AS T3, NHACUNGCAP,MATHANG WHERE MATHANG.MANCC=NHACUNGCAP.MANCC AND T3.MAMH=MATHANG.MAMH " + SQL1 + "  group by MATHANG.MANCC,TENNCC";
            string SQL = "SELECT TRAHOADONNHAP.MANCC,TENNCC,SUM(TIENPHAITRA) AS DOANHTHU, SUM(-KHOILUONG) AS KHOILUONG FROM TRAHOADONNHAP, NHACUNGCAP,(SELECT SUM(NHAPXUAT*KLDVT) as KHOILUONG,MAHD FROM TONKHO,MATHANG WHERE MATHANG.MAMH=TONKHO.MAMH GROUP BY MAHD) AS TONKHO WHERE TONKHO.MAHD=TRAHOADONNHAP.MAHDN AND TRAHOADONNHAP.MANCC=NHACUNGCAP.MANCC AND NGAYNHAP BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' AND TYPE=1  AND TRAHOADONNHAP.MAKHO='" + PublicVariable.MAKHO + "'   " + SQL1 + " GROUP BY TRAHOADONNHAP.MANCC, TENNCC";
            
            return getdata(SQL);
        }
        public DataTable getDoanhsonv(clDTO dto)
        {
            string SQL = "SELECT TENNV,DONVITINH,KLDVT,-SUM(KLXUAT)AS SLXUAT,-SUM(KLTRANHAP) AS SLTRANHAP,-SUM(KLXUAT)*KLDVT AS KLXUAT,-SUM(KLTRANHAP)*KLDVT AS KLTRANHAP,-SUM(XUAT) AS TIENXUAT, -SUM(TRANHAP) AS TIENTRANHAP FROM (select  MANV,MAMH, (CASE WHEN T2.MANHAPXUAT<>'X' THEN 0 ELSE SUM(GIATIEN) END) AS XUAT,(CASE WHEN T2.MANHAPXUAT<>'X' THEN 0 ELSE SUM(NHAPXUAT) END) AS KLXUAT,(CASE WHEN T2.MANHAPXUAT<>'TN' THEN 0 ELSE SUM(GIATIEN) END) AS TRANHAP,(CASE WHEN T2.MANHAPXUAT<>'TN' THEN 0 ELSE SUM(NHAPXUAT) END) AS KLTRANHAP  FROM TONKHO as T2 WHERE NGAY BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' AND T2.MAKHO='" + PublicVariable.MAKHO + "'  AND TYPE=1  group by MANV,MAMH, MANHAPXUAT) AS T3, NHANVIEN,MATHANG,DONVITINH WHERE NHANVIEN.MANV=T3.MANV AND T3.MAMH=MATHANG.MAMH AND MATHANG.MADVT=DONVITINH.MADVT group by TENNV,DONVITINH,KLDVT";
            return getdata(SQL);
        }
        public DataTable getcpmuahangsp(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MAMH != "" && dto.MAMH != null)
            {
                SQL1 = " AND MATHANG.MAMH='" + dto.MAMH + "'  ";
            }
            string SQL = "SELECT MATHANG.MAMH,TENMH,TENNCC,DONVITINH,KLDVT,SUM(KLNHAP)AS SLNHAP,SUM(KLTRAXUAT) AS SLTRAXUAT,SUM(KLNHAP)*KLDVT AS KLNHAP,SUM(KLTRAXUAT)*KLDVT AS KLTRAXUAT,SUM(NHAP) AS TIENMUAHANG, SUM(TRAXUAT) AS TIENTRAXUAT FROM (select  MAMH, (CASE WHEN T2.MANHAPXUAT<>'N' THEN 0 ELSE SUM(GIATIEN) END) AS NHAP,(CASE WHEN T2.MANHAPXUAT<>'N' THEN 0 ELSE SUM(NHAPXUAT) END) AS KLNHAP,(CASE WHEN T2.MANHAPXUAT<>'TX' THEN 0 ELSE SUM(GIATIEN) END) AS TRAXUAT,(CASE WHEN T2.MANHAPXUAT<>'TX' THEN 0 ELSE SUM(NHAPXUAT) END) AS KLTRAXUAT  FROM TONKHO as T2 WHERE NGAY BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' AND T2.MAKHO='" + PublicVariable.MAKHO + "' group by MAMH, MANHAPXUAT) AS T3, NHACUNGCAP,MATHANG,DONVITINH WHERE MATHANG.MANCC=NHACUNGCAP.MANCC AND T3.MAMH=MATHANG.MAMH AND MATHANG.MADVT=DONVITINH.MADVT " + SQL1 + " group by MATHANG.MAMH,TENMH,TENNCC,DONVITINH,KLDVT";
            return getdata(SQL);
        }
        public DataTable getDoanhsosp(clDTO dto)
        {
            string SQL1 = "";
            if (dto.MAMH != "" && dto.MAMH != null)
            {
                SQL1 = " AND MATHANG.MAMH='" + dto.MAMH + "'  ";
            }

            string SQL = "SELECT MATHANG.MAMH,TENMH,TENNCC,DONVITINH,KLDVT,SUM(KLXUAT)AS SLXUAT,SUM(KLTRANHAP) AS SLTRANHAP,SUM(KLXUAT)*KLDVT AS KLXUAT,SUM(KLTRANHAP)*KLDVT AS KLTRANHAP,SUM(XUAT) AS TIENXUAT, SUM(TRANHAP) AS TIENTRANHAP FROM (select  MAMH, (CASE WHEN T2.MANHAPXUAT<>'X' THEN 0 ELSE SUM(GIATIEN) END) AS XUAT,(CASE WHEN T2.MANHAPXUAT<>'X' THEN 0 ELSE SUM(NHAPXUAT) END) AS KLXUAT,(CASE WHEN T2.MANHAPXUAT<>'TN' THEN 0 ELSE SUM(GIATIEN) END) AS TRANHAP,(CASE WHEN T2.MANHAPXUAT<>'TN' THEN 0 ELSE SUM(NHAPXUAT) END) AS KLTRANHAP  FROM TONKHO as T2 WHERE NGAY BETWEEN '" + dto.NGAYBD + "' AND '" + dto.NGAYKT + "' AND T2.MAKHO='" + PublicVariable.MAKHO + "' group by MAMH, MANHAPXUAT) AS T3, NHACUNGCAP,MATHANG,DONVITINH WHERE MATHANG.MANCC=NHACUNGCAP.MANCC AND T3.MAMH=MATHANG.MAMH AND MATHANG.MADVT=DONVITINH.MADVT " + SQL1 + " group by MATHANG.MAMH,TENMH,TENNCC,DONVITINH,KLDVT";
            return getdata(SQL);
        }
        public DataTable testLogin(clDTO dto)
        {
            string SQL="select 	MANV,MABP,USERNAMES,PASSWORD,CHUCVU,TENNV,DIACHI,NGAYSINH,SCMND,SDT,TINHTRANG from  NHANVIEN"
            + " where 	PASSWORD='"+dto.MATKHAU+"' and USERNAMES='"+dto.TENDANGNHAP+"'";
            return getdata(SQL);
        }

       
    }
}
